#!/usr/bin/env node
/**
 * Writes pos-version.json (public + backend root) and src/posBuildInfo.ts
 * before each dev/build so the running bundle knows its own build id.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));

let commit = "dev";
try {
  commit = execSync("git rev-parse --short HEAD", {
    cwd: path.join(root, "../.."),
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
} catch {
  // offline / shallow clone — keep "dev"
}

const now = new Date();
const pad = (n) => String(n).padStart(2, "0");
const datePart = `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())}`;
const timePart = `${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}`;
const build = `${datePart}-${timePart}-${commit}`;

const info = {
  version: pkg.version,
  build,
  commit,
  built_at: now.toISOString(),
};

const json = `${JSON.stringify(info, null, 2)}\n`;

mkdirSync(path.join(root, "public"), { recursive: true });
writeFileSync(path.join(root, "public", "pos-version.json"), json);

writeFileSync(
  path.join(root, "src", "posBuildInfo.ts"),
  `// Auto-generated by scripts/generate-version.mjs — do not edit manually.\nexport const POS_BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

// pos-version.json is copied to backend/public/pos/ only via dist deploy
// (scripts/build-all.sh). Do not write it there here — that desyncs the
// manifest from the shipped JS bundle and causes endless "Update Now" banners.

console.log(`POS build: v${info.version} · ${info.build}`);
