import { createContext, useContext, useEffect, type ReactNode } from "react";

/** English UI copy. Keys retained so a future language can be re-added without reshaping call sites. */
type Translations = Record<string, string>;

const TRANSLATIONS: Translations = {
  "menu.title": "Our Menu",
  "menu.search": "Search menu…",
  "cart.title": "Your Cart",
  "cart.empty": "Your cart is empty — add something to get started",
  "cart.checkout": "Proceed to Checkout",
  "checkout.title": "Checkout",
  "reserve.title": "Reserve a Table",
  "order.status.pending": "Order Received",
  "order.status.preparing": "Being Prepared",
  "order.status.ready": "Ready",
  "order.status.completed": "Completed",
  "closed.message": "We are currently closed",
  "cart.view": "View cart",
  "order.status.payment_pending": "Awaiting payment",
  "order.status.paid": "Confirmed",
  "order.status.cancelled": "Cancelled",
  "nav.home": "Home",
  "nav.menu": "Menu",
  "nav.orders": "Orders",
  "nav.rewards": "Rewards",
  "nav.account": "Account",
  "nav.aria": "Main navigation",
  "common.back": "Back",
  "common.change": "Change",
  "common.try_again": "Try again",
  "common.loading": "Loading",
  "common.skip_content": "Skip to content",
  "common.on": "On",
  "common.off": "Off",
  "sheet.close": "Close",
  "sheet.dialog": "Dialog",
  "error.generic_title": "Something went wrong",
  "orders.active_capsule": "Order",
  "orders.active_badge": "Active order",
  "rewards.title": "Rewards",
  "rewards.stub_title": "Loyalty & rewards",
  "rewards.stub_body": "Sign in to see your points. Gift cards and loyalty redemption stay at checkout.",
  "rewards.stub_cta": "Go to account",
  "rewards.checkout_cta": "Use at checkout",
  "home.greeting_hello": "Hello",
  "home.greeting_named": "Hello, {name}",
  "home.greeting_sub": "What would you like today?",
  "account.settings": "Settings",
  "account.dark_mode": "Dark mode",
  "account.more_links": "More",
  "account.link_preorder": "Pre-Order",
  "account.link_reservations": "Reservations",
  "account.link_hours": "Hours",
  "account.link_contact": "Contact",
  "account.link_about": "About",
  "account.link_privacy": "Privacy",
  "account.link_orders": "Order history",
  "account.link_terms": "Terms & Conditions",
  "account.link_refund": "Refund Policy",
  "account.prayer_times": "Prayer times",
  "mode.pickup": "Pickup",
  "mode.delivery": "Delivery",
  "mode.toggle_aria": "Order mode",
  "menu.categories": "Categories",
  "menu.clear_filters": "Clear filters",
  "menu.toast_prune_one": "{n} cart item removed for this order mode.",
  "menu.toast_prune_many": "{n} cart items removed for this order mode.",
  "menu.toast_delivery_fallback": "No delivery items right now — showing pickup menu instead.",
  "cart.edit": "Edit",
  "common.cancel": "Cancel",
  "common.clear": "Clear",
  "menu.search_aria": "Search menu",
  "menu.search_results_count": "{n} results",
  "menu.popular": "Popular",
  "menu.no_results": "No results for '{q}'",
  "menu.sort_price_low": "Price ↑",
  "menu.sort_price_high": "Price ↓",
  "menu.filter_all": "All items",
  "menu.filter_specials": "Specials",
  "menu.filter_all_diets": "All diets",
  "menu.open_search": "Search",
  "menu.unavailable": "UNAVAILABLE",
  "menu.out_of_stock": "Out of stock",
  "menu.view_item": "View details for {name}",
  "a11y.announcement": "Site announcement",
  // ── Phase 4 Home strings ───────────────────────────────────────────────────
  "home.sign_in": "Sign in",
  "home.chip_rewards": "points",
  "home.chip_sign_in_points": "Sign in to earn points",
  "home.chip_order": "Track order",
  "home.chip_no_order": "No active order",
  "home.chip_specials": "specials today",
  "home.specials_title": "Today's specials",
  "home.specials_subtitle": "Limited-time deals, today only",
  "home.see_all": "See all →",
  "header.back_menu": "← Menu",
  "header.back_home": "← Home",
  "header.home_aria": "{name} — Home",
  "status.open": "Online ordering open",
  "status.open_closes": "Online ordering open · Closes {time}",
  "status.closed": "Online ordering closed",
  "status.closed_opens": "Online ordering closed · Opens {time}",
  "menu.toast_sign_in_favourites": "Sign in to save favourites",
  "menu.delivery_fallback_banner": "Delivery is unavailable for these items — you're viewing the pickup menu.",
  "cart.subtotal": "Subtotal",
  "cart.subtotal_excl": "(excl. tax & fees)",
  "cart.closed_cta": "Closed — not taking orders right now",
  "cart.add_items_cta": "Add items to continue",
  "cart.free_delivery_add": "Add MVR {amount} for free delivery",
  "cart.free_delivery_met": "Over the free-delivery threshold — final fee confirmed at checkout",
  "cart.earn_preview": "~{n} pts you'll earn",
  "cart.kitchen_wait": "Kitchen wait ~{n} min",
  "cart.upsell_title": "Add to your order",
  "home.order_again": "Order again",
  "home.reorder": "Order again",
  "home.reordering": "Adding…",
  "home.promo_region": "Promotional banner",
  "home.mode_delivery_hint": "Delivered to your door in 30–45 min",
  "home.mode_pickup_hint": "Pick up at our Kalaafaanu Hingun location",
  "home.footer_thanks": "Thank you for choosing Bake & Grill. Made with love in Malé.",
  "home.footer_whatsapp": "WhatsApp",
  "home.footer_viber": "Viber",
  "home.corporate_thanks": "Thanks — we'll be in touch!",
  "home.corp_name_required": "Name and phone are required.",
  "home.corp_min_guests": "Minimum {n} guests for office orders.",
  "home.corp_ph_name": "Your name *",
  "home.corp_ph_phone": "Phone *",
  "home.corp_ph_company": "Company / organisation",
  "home.corp_ph_headcount": "Headcount (min {n})",
  "home.corp_ph_notes": "Event date, dietary needs, delivery address…",
  "home.corp_sending": "Sending…",
  "home.corp_submit": "Request a quote →",
  "home.mode_region": "Choose order mode",
  "prayer.aria": "Prayer times",
  "prayer.title": "Prayer Times",
  "prayer.next_in": "next in {t}",
  "prayer.use_location": "Use my location",
  "prayer.change_island": "Change island",
  "prayer.search_island": "Search island or atoll…",
  "prayer.no_islands": "No islands found",
  "prayer.unavailable": "Prayer times unavailable",
  "prayer.offline_cached": "Offline — cached times",
  "prayer.cached": "Showing cached times",
  // ── Phase 5 Checkout accordion strings ────────────────────────────────────
  "checkout.acc_order_type": "Order Type",
  "checkout.acc_pickup": "Pickup Time",
  "checkout.acc_delivery": "Delivery Details",
  "checkout.acc_discounts": "Discounts & Rewards",
  "checkout.acc_notes": "Special Instructions",
  "checkout.acc_payment": "Payment",
  "checkout.acc_payment_summary": "BML",
  "checkout.empty_cart": "Your cart is empty. Add some items first.",
  "checkout.browse_menu": "Browse the menu",
  "checkout.processing": "Processing…",
  "checkout.gate_closed": "Online ordering is closed",
  "checkout.gate_closed_sub": "Online ordering is currently unavailable. Please check back later.",
  "checkout.place_no_payment": "Place order — no payment due",
  "checkout.pay_bml": "Pay MVR {amount} with BML",
  "checkout.asap": "ASAP",
  "checkout.terms_prefix": "I agree to the",
  "checkout.terms_and": ", and",
  "checkout.whatsapp_help": "Message us on WhatsApp",
  "checkout.referral_pending": "Referral discount is estimated — final amount confirmed when your order is created.",
  "checkout.kitchen_wait": "Kitchen wait ~{n} min",
  "checkout.hi_name": "Hi, {name}",
  "checkout.contact_whatsapp": "Contact us on WhatsApp",
  "checkout.contact_viber": "Contact us on Viber",
  // ── Phase 6 Orders tab strings ────────────────────────────────────────────
  "orders.active_section": "Active Orders",
  "orders.past_section": "Past Orders",
  "orders.empty_title": "No orders yet",
  "orders.empty_body": "Start your first order and it will appear here.",
  "orders.empty_cta": "Browse the menu",
  "orders.sign_in_prompt": "Sign in to view your order history.",
  "orders.track": "Track",
  "orders.view": "View",
  "orders.recent_title": "Recent orders",
  "orders.see_all": "See all orders →",
  "orders.none_recent": "No recent orders yet",
  "orders.reorder_added": "{n} item(s) added to cart",
  "orders.reorder_fail": "Could not load that order. Please try again.",
  // ── Phase 5 PR3 AuthBlock strings ──────────────────────────────────────────
  "auth.title_phone": "Your phone number",
  "auth.sub_phone": "Enter your Maldives number to sign in.",
  "auth.continue": "Continue →",
  "auth.checking": "Checking…",
  "auth.guest_cta": "Checkout as guest — no OTP needed",
  "auth.title_password": "Welcome back",
  "auth.signing_as": "Signing in as +960 {phone}",
  "auth.forgot": "Forgot password?",
  "auth.different_number": "← Use a different number",
  "auth.sign_in": "Sign in →",
  "auth.signing_in": "Signing in…",
  "auth.title_otp": "Enter your code",
  "auth.otp_sent": "Code sent to +960 {phone}",
  "auth.confirm": "Confirm →",
  "auth.verifying": "Verifying…",
  "auth.resend": "Resend code",
  "auth.resend_in": "Resend in {n}s",
  "auth.title_guest": "Guest checkout",
  "auth.sub_guest": "Enter your name and phone — no account needed.",
  "auth.back_otp": "← Sign in with OTP instead",
  "auth.guest_continue": "Continue to checkout →",
  "auth.guest_starting": "Starting…",
  "auth.title_profile": "One last step",
  "auth.sub_profile": "Set your name and a password so you can sign in next time.",
  "auth.create_account": "Create account →",
  "auth.saving": "Saving…",
  "auth.skip_profile": "Skip for now — go to checkout",
  "auth.title_forgot": "Reset your password",
  "auth.sub_forgot": "We'll send a code to verify it's you.",
  "auth.send_reset": "Send reset code →",
  "auth.sending": "Sending…",
  "auth.back_pass": "← Back to sign in",
  "auth.title_forgot_otp": "Enter the code",
  "auth.reset_sent": "Reset code sent to +960 {phone}",
  "auth.title_new_pass": "New password",
  "auth.new_pass_for": "New password for +960 {phone}",
  "auth.set_password": "Set password →",
  // ── Phase 6 Account §21 hub strings ──────────────────────────────────────
  "account.title": "My Account",
  "account.greeting": "Hi, {name}",
  "account.profile": "Profile",
  "account.addresses": "Addresses",
  "account.orders": "Order History",
  "account.bookings": "Bookings",
  "account.extras": "Account extras",
  "account.loyalty": "Loyalty",
  "account.credit": "Credit Account",
  "account.deposit": "Deposit Balance",
  "account.favourites": "Favourites",
  "account.preorders": "Pre-orders",
  "account.reviews": "Reviews",
  "account.push_notifications": "Push notifications",
  "account.logout": "Sign out",
  "account.logout_confirm": "Sign out of your account?",
  "account.link_whatsapp": "WhatsApp us",
  "account.link_viber": "Message on Viber",
  "account.referrals": "Referrals",
  // ── Phase 6 RewardsPage strings ────────────────────────────────────────────
  "rewards.sign_in_teaser": "Sign in to see your loyalty points and referral code",
  "rewards.points_available": "points available",
  "rewards.approx_mvr": "≈ MVR {value}",
  "rewards.tier_member": "{tier} Member",
  "rewards.progress_to_next": "{n} pts to reach {tier}",
  "rewards.at_max_tier": "Maximum tier reached",
  "rewards.use_at_checkout": "Use points at checkout →",
  "rewards.referral_title": "Refer a friend",
  "rewards.referral_body": "Share your code. Your friend saves on their first order.",
  "rewards.referral_copy": "Copy code",
  "rewards.referral_copied": "Copied!",
  "rewards.referral_share": "Share",
  "rewards.referral_uses_one": "1 friend referred",
  "rewards.referral_uses_many": "{n} friends referred",
  "rewards.how_title": "How points work",
  "rewards.how_earn": "Earn {rate} point per MVR 1 spent on food.",
  "rewards.how_redeem": "{rate} points = MVR 1 off at checkout.",
  "rewards.how_min": "Minimum {min} points needed to redeem.",
  "rewards.how_max_pct": "Points can cover up to {pct}% of your order total.",
  "rewards.how_expand": "Details",
  "rewards.how_collapse": "Close",
};

type LanguageContextType = {
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType>({
  t: (k) => k,
});

const LANG_STORAGE_KEY = "bakegrill_lang";

export function LanguageProvider({ children }: { children: ReactNode }) {
  useEffect(() => {
    // Clear legacy language preference (pre–English-only UI).
    try { localStorage.removeItem(LANG_STORAGE_KEY); } catch { /* private mode / quota */ }
    document.documentElement.lang = "en";
    document.documentElement.dir = "ltr";
  }, []);

  const t = (key: string): string => TRANSLATIONS[key] ?? key;

  return (
    <LanguageContext.Provider value={{ t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
