import { createContext, useContext, useEffect, useState, type ReactNode } from "react";

/** English UI copy. Keys retained so a future language can be re-added without reshaping call sites. */
type Translations = Record<string, string>;

const TRANSLATIONS: Translations = {
  "menu.title": "Our Menu",
  "menu.search": "Search menu…",
  "cart.title": "Your Cart",
  "cart.empty": "Your cart is empty — add something to get started",
  "cart.checkout": "Proceed to Checkout",
  "cart.checkout_short": "Checkout",
  "cart.checkout_tomorrow": "Checkout — collect tomorrow",
  "checkout.title": "Checkout",
  "reserve.title": "Reserve a Table",
  "order.status.pending": "Order Received",
  "order.status.preparing": "Being Prepared",
  "order.status.ready": "Ready",
  "order.status.completed": "Completed",
  "closed.message": "We are currently closed",
  "cart.view": "View cart",
  "order.status.payment_pending": "Awaiting payment",
  "order.status.paid": "Confirmed",
  "order.status.cancelled": "Cancelled",
  "nav.home": "Home",
  "nav.menu": "Menu",
  "nav.orders": "Orders",
  "nav.preorder": "Pre-order",
  "nav.rewards": "Rewards",
  "nav.account": "Account",
  "nav.gifts": "Gifts",
  "nav.aria": "Main navigation",
  "common.back": "Back",
  "common.change": "Change",
  "common.try_again": "Try again",
  "common.loading": "Loading",
  "common.skip_content": "Skip to content",
  "common.on": "On",
  "common.off": "Off",
  "sheet.close": "Close",
  "sheet.dialog": "Dialog",
  "error.generic_title": "Something went wrong",
  "error.generic_body": "This page encountered an unexpected error.",
  "error.reload": "Reload page",
  "error.go_menu": "Go to menu",
  "notfound.title": "Page not found",
  "notfound.body": "The page you're looking for doesn't exist.",
  "notfound.home": "Back to home",
  "orders.load_fail": "Could not load orders. Please try again.",
  "orders.more_items": "+{n} more",
  "home.corp_headline_default": "Events & catering",
  "home.corp_sub_default": "Plan office breakfasts and celebrations with a structured quote — or order catering trays for today from the menu.",
  "privacy.sec_intro": "Introduction",
  "privacy.sec_collect": "Information We Collect",
  "privacy.sec_use": "How We Use Your Information",
  "privacy.sec_sms": "SMS Communications",
  "privacy.sec_payment": "Card Payment Security",
  "privacy.sec_security": "Data Security",
  "privacy.sec_sharing": "Data Sharing",
  "privacy.sec_rights": "Your Rights",
  "privacy.sec_contact": "Contact Us",
  "orders.active_capsule": "Order",
  "orders.active_badge": "Active order",
  "rewards.title": "Rewards",
  "rewards.stub_title": "Loyalty & rewards",
  "rewards.stub_body": "Sign in to see your points. Gift cards and loyalty redemption stay at checkout.",
  "rewards.stub_cta": "Go to account",
  "rewards.checkout_cta": "Use at checkout",
  "home.greeting_hello": "Hello",
  "home.greeting_named": "Hello, {name}",
  "home.greeting_sub": "What would you like today?",
  "account.settings": "Settings",
  "account.dark_mode": "Dark mode",
  "account.more_links": "More",
  "account.link_preorder": "Pre-Order",
  "account.link_reservations": "Reservations",
  "account.link_hours": "Hours",
  "account.link_contact": "Contact",
  "account.link_about": "About",
  "account.link_privacy": "Privacy",
  "account.link_orders": "Order history",
  "account.link_terms": "Terms & Conditions",
  "account.link_refund": "Refund Policy",
  "account.prayer_times": "Prayer times",
  "mode.pickup": "Pickup",
  "mode.delivery": "Delivery",
  "mode.toggle_aria": "Order mode",
  "menu.categories": "Categories",
  "menu.clear_filters": "Clear filters",
  "menu.toast_prune_one": "{n} cart item removed for this order mode.",
  "menu.toast_prune_many": "{n} cart items removed for this order mode.",
  "menu.toast_delivery_fallback": "No delivery items right now — showing pickup menu instead.",
  "cart.edit": "Edit",
  "common.cancel": "Cancel",
  "common.clear": "Clear",
  "menu.search_aria": "Search menu",
  "menu.search_results_count": "{n} results",
  "menu.popular": "Popular",
  "menu.no_results": "No results for '{q}'",
  "menu.sort_price_low": "Price ↑",
  "menu.sort_price_high": "Price ↓",
  "menu.filter_all": "All items",
  "menu.filter_specials": "Specials",
  "menu.filter_all_diets": "All diets",
  "menu.open_search": "Search",
  "menu.unavailable": "Unavailable",
  "menu.out_of_stock": "Sold out",
  "menu.unavailable_today": "Unavailable today",
  "menu.opens_at": "Opens at {time}",
  "menu.channel_unavailable": "Not available for pickup / delivery",
  "menu.only_n_left": "Only {n} left",
  "menu.few_left": "Few left",
  "menu.view_item": "View details for {name}",
  "menu.can_order_tomorrow": "Can be ordered for tomorrow",
  "menu.banner_closed_short": "Closed",
  "menu.banner_opens_short": "Opens {time}",
  "menu.banner_tomorrow_short": "Some items for tomorrow",
  "cart.closed_tomorrow_tip": "Add only Tomorrow items to order for tomorrow.",
  "a11y.announcement": "Site announcement",
  // ── Phase 4 Home strings ───────────────────────────────────────────────────
  "home.sign_in": "Sign in",
  "home.chip_rewards": "points",
  "home.chip_sign_in_points": "Sign in to earn points",
  "home.chip_order": "Track order",
  "home.chip_no_order": "No active order",
  "home.specials_title": "Today's specials",
  "home.specials_subtitle": "Limited-time deals, today only",
  "home.see_all": "See all →",
  "header.back_menu": "← Menu",
  "header.back_home": "← Home",
  "header.home_aria": "{name} — Home",
  "header.website_aria": "{name} — Main website",
  "account.link_website": "Main website",
  "status.open": "Online ordering open",
  "status.open_closes": "Online ordering open · Closes {time}",
  "status.closed": "Online ordering closed",
  "status.closed_opens": "Online ordering closed · Opens {time}",
  "menu.toast_sign_in_favourites": "Sign in to save favourites",
  "menu.delivery_fallback_banner": "Delivery is unavailable for these items — you're viewing the pickup menu.",
  "cart.subtotal": "Subtotal",
  "cart.subtotal_excl": "(excl. tax & fees)",
  "cart.closed_cta": "Online ordering is off",
  "cart.closed_cta_short": "Ordering is closed",
  "cart.opens_at_cta": "Ordering opens at {time}",
  "menu.pickup_unavailable": "Pickup is currently unavailable",
  "menu.delivery_unavailable": "Delivery is currently unavailable",
  "cart.add_items_cta": "Add items to continue",
  "cart.free_delivery_add": "Add MVR {amount} for free delivery",
  "cart.free_delivery_met": "Over the free-delivery threshold — final fee confirmed at checkout",
  "cart.earn_preview": "~{n} pts you'll earn",
  "cart.kitchen_wait": "Kitchen wait ~{n} min",
  "cart.upsell_title": "Add to your order",
  "home.order_again": "Order again",
  "home.reorder": "Order again",
  "home.reordering": "Adding…",
  "home.promo_region": "Promotional banner",
  "home.mode_delivery_hint": "Delivered to your door in 30–45 min",
  "home.mode_pickup_hint": "Pick up at our Kalaafaanu Hingun location",
  "home.footer_thanks": "Thank you for choosing Bake & Grill. Made with love in Malé.",
  "home.footer_whatsapp": "WhatsApp",
  "home.footer_viber": "Viber",
  "home.corporate_thanks": "Thanks — we'll be in touch!",
  "home.corp_name_required": "Name and phone are required.",
  "home.corp_min_guests": "Minimum {n} guests for office orders.",
  "home.corp_ph_name": "Your name *",
  "home.corp_ph_phone": "Phone *",
  "home.corp_ph_company": "Company / organisation",
  "home.corp_ph_headcount": "Headcount (min {n})",
  "home.corp_ph_notes": "Event date, dietary needs, delivery address…",
  "home.corp_sending": "Sending…",
  "home.corp_submit": "Request a quote →",
  "home.mode_region": "Choose order mode",
  "prayer.aria": "Prayer times",
  "prayer.title": "Prayer Times",
  "prayer.next_in": "next in {t}",
  "prayer.use_location": "Use my location",
  "prayer.change_island": "Change island",
  "prayer.search_island": "Search island or atoll…",
  "prayer.no_islands": "No islands found",
  "prayer.unavailable": "Prayer times unavailable",
  "prayer.offline_cached": "Offline — cached times",
  "prayer.cached": "Showing cached times",
  // ── Phase 5 Checkout accordion strings ────────────────────────────────────
  "checkout.acc_order_type": "Order Type",
  "checkout.acc_pickup": "Pickup Time",
  "checkout.acc_delivery": "Delivery Details",
  "checkout.acc_discounts": "Discounts & Rewards",
  "checkout.acc_notes": "Special Instructions",
  "checkout.acc_payment": "Payment",
  "checkout.acc_payment_summary": "BML",
  "checkout.empty_cart": "Your cart is empty. Add some items first.",
  "checkout.browse_menu": "Browse the menu",
  "checkout.processing": "Processing…",
  "checkout.gate_closed": "Online ordering is closed",
  "checkout.gate_closed_sub": "Online ordering is currently unavailable. Please check back later.",
  "checkout.place_no_payment": "Place order — no payment due",
  "checkout.pay_bml": "Pay MVR {amount} with BML",
  "checkout.asap": "ASAP",
  "checkout.terms_prefix": "I agree to the",
  "checkout.terms_and": ", and",
  "checkout.whatsapp_help": "Message us on WhatsApp",
  "checkout.referral_pending": "Referral discount is estimated — final amount confirmed when your order is created.",
  "checkout.kitchen_wait": "Kitchen wait ~{n} min",
  "checkout.hi_name": "Hi, {name}",
  "checkout.contact_whatsapp": "Contact us on WhatsApp",
  "checkout.contact_viber": "Contact us on Viber",
  // ── Phase 6 Orders tab strings ────────────────────────────────────────────
  "orders.active_section": "Active Orders",
  "orders.type_gift_card": "Gift card",
  "orders.gift_purchased": "Purchased",
  "orders.gift_payment_pending": "Payment pending",
  "orders.past_section": "Past Orders",
  "orders.empty_title": "No orders yet",
  "orders.empty_body": "Start your first order and it will appear here.",
  "orders.empty_cta": "Browse the menu",
  "orders.sign_in_prompt": "Sign in to view your order history.",
  "orders.track": "Track",
  "orders.view": "View",
  "orders.recent_title": "Recent orders",
  "orders.see_all": "See all orders →",
  "orders.none_recent": "No recent orders yet",
  "orders.reorder_added": "{n} item(s) added to cart",
  "orders.reorder_fail": "Could not load that order. Please try again.",
  // ── Phase 5 PR3 AuthBlock strings ──────────────────────────────────────────
  "auth.title_phone": "Your phone number",
  "auth.sub_phone": "Enter your Maldives number to sign in.",
  "auth.continue": "Continue →",
  "auth.checking": "Checking…",
  "auth.guest_cta": "Checkout as guest — no OTP needed",
  "auth.title_password": "Welcome back",
  "auth.signing_as": "Signing in as +960 {phone}",
  "auth.forgot": "Forgot password?",
  "auth.different_number": "← Use a different number",
  "auth.sign_in": "Sign in →",
  "auth.signing_in": "Signing in…",
  "auth.title_otp": "Enter your code",
  "auth.otp_sent": "Code sent to +960 {phone}",
  "auth.confirm": "Confirm →",
  "auth.verifying": "Verifying…",
  "auth.resend": "Resend code",
  "auth.resend_in": "Resend in {n}s",
  "auth.title_guest": "Guest checkout",
  "auth.sub_guest": "Enter your name and phone — no account needed.",
  "auth.back_otp": "← Sign in with OTP instead",
  "auth.guest_continue": "Continue to checkout →",
  "auth.guest_starting": "Starting…",
  "auth.title_profile": "One last step",
  "auth.sub_profile": "Set your name and a password so you can sign in next time.",
  "auth.create_account": "Create account →",
  "auth.saving": "Saving…",
  "auth.skip_profile": "Skip for now — go to checkout",
  "auth.title_forgot": "Reset your password",
  "auth.sub_forgot": "We'll send a code to verify it's you.",
  "auth.send_reset": "Send reset code →",
  "auth.sending": "Sending…",
  "auth.back_pass": "← Back to sign in",
  "auth.title_forgot_otp": "Enter the code",
  "auth.reset_sent": "Reset code sent to +960 {phone}",
  "auth.title_new_pass": "New password",
  "auth.new_pass_for": "New password for +960 {phone}",
  "auth.set_password": "Set password →",
  // ── Phase 6 Account §21 hub strings ──────────────────────────────────────
  "account.title": "My Account",
  "account.greeting": "Hi, {name}",
  "account.profile": "Profile",
  "account.addresses": "Addresses",
  "account.orders": "Order History",
  "account.bookings": "Bookings",
  "account.extras": "Account extras",
  "account.loyalty": "Loyalty",
  "account.credit": "Credit Account",
  "account.deposit": "Deposit Balance",
  "account.favourites": "Favourites",
  "account.preorders": "Pre-orders",
  "account.reviews": "Reviews",
  "account.push_notifications": "Push notifications",
  "account.logout": "Sign out",
  "account.logout_confirm": "Sign out of your account?",
  "account.link_whatsapp": "WhatsApp us",
  "account.link_viber": "Message on Viber",
  "account.referrals": "Referrals",
  // ── Phase 6 RewardsPage strings ────────────────────────────────────────────
  "rewards.sign_in_teaser": "Sign in to see your loyalty points and referral code",
  "rewards.points_available": "points available",
  "rewards.approx_mvr": "≈ MVR {value}",
  "rewards.tier_member": "{tier} Member",
  "rewards.progress_to_next": "{n} pts to reach {tier}",
  "rewards.at_max_tier": "Maximum tier reached",
  "rewards.use_at_checkout": "Use points at checkout →",
  "rewards.referral_title": "Refer a friend",
  "rewards.referral_body": "Share your code. Your friend saves on their first order.",
  "rewards.referral_copy": "Copy code",
  "rewards.referral_copied": "Copied!",
  "rewards.referral_share": "Share",
  "rewards.referral_uses_one": "1 friend referred",
  "rewards.referral_uses_many": "{n} friends referred",
  "rewards.how_title": "How points work",
  "rewards.how_earn": "Earn {rate} point per MVR 1 spent on food.",
  "rewards.how_redeem": "{rate} points = MVR 1 off at checkout.",
  "rewards.how_min": "Minimum {min} points needed to redeem.",
  "rewards.how_max_pct": "Points can cover up to {pct}% of your order total.",
  "rewards.how_expand": "Details",
  "rewards.how_collapse": "Close",

  // ── Auth form labels / errors ──────────────────────────────────────
  "auth.ph_phone": "7xxxxxxx",
  "auth.label_name": "Your name",
  "auth.ph_name": "Ahmed Ali",
  "auth.label_phone": "Phone number",
  "auth.ph_password": "Your password",
  "auth.label_email": "Email",
  "auth.optional": "(optional)",
  "auth.ph_email": "you@example.com",
  "auth.label_password": "Password",
  "auth.ph_password_min": "At least 6 characters",
  "auth.label_confirm_password": "Confirm password",
  "auth.ph_password_repeat": "Repeat your password",
  "auth.label_new_password": "New password",
  "auth.err_name_required": "Please enter your name.",
  "auth.err_password_mismatch": "Passwords don't match.",
  "auth.hint_code_sent": "New code sent.",
  "auth.privacy_line": "Used for order updates only — we never sell your number or spam you.",
  "auth.digit_aria": "Digit {n}",

  // ── Checkout form / summary ────────────────────────────────────────
  "checkout.type_pickup": "Pickup",
  "checkout.type_delivery": "Delivery",
  "checkout.delivery_unavailable": "Delivery is not available right now. Please choose pickup.",
  "checkout.pickup_loading": "Loading available times…",
  "checkout.pickup_full": "Pickup slots are full or unavailable right now — we'll prepare your order as soon as possible after payment.",
  "checkout.pickup_choose": "Choose when you'd like to collect your order (optional).",
  "checkout.delivery_fee_prefix": "Delivery fee:",
  "checkout.zone_rate": "Zone rate for {island}: MVR {fee}",
  "checkout.standard_rate": "Standard rate: MVR {fee}",
  "checkout.estimated": "Estimated {eta}",
  "checkout.free_qualifies": "Your order qualifies for free delivery (orders over MVR {n}).",
  "checkout.free_add_more": "Free delivery on orders over MVR {n} — add MVR {amount} more to qualify.",
  "checkout.saved_address": "Saved address",
  "checkout.new_address": "Use a new address",
  "checkout.default_suffix": "(default)",
  "checkout.label_address": "Address *",
  "checkout.ph_address": "House / Flat number, Street",
  "checkout.label_address2": "Address line 2",
  "checkout.ph_address2": "Building name (optional)",
  "checkout.label_island": "Island *",
  "checkout.ph_island": "Malé",
  "checkout.label_maps": "Google Maps / location link",
  "checkout.ph_maps": "https://maps.google.com/...",
  "checkout.label_contact_name": "Contact name *",
  "checkout.ph_contact_name": "Full name",
  "checkout.label_contact_phone": "Contact phone *",
  "checkout.ph_contact_phone": "7xxxxxxx",
  "checkout.label_delivery_notes": "Delivery notes",
  "checkout.ph_delivery_notes": "Any special instructions for the rider",
  "checkout.save_address": "Save this address to my account",
  "checkout.label_address_label": "Address label",
  "checkout.ph_address_label": "Home, Office, etc.",
  "checkout.ph_notes": "Allergies, special requests, or notes for the kitchen",
  "checkout.promo_code": "Promo Code",
  "checkout.remove": "Remove",
  "checkout.apply": "Apply",
  "checkout.check": "Check",
  "checkout.promo_pending": "applied at checkout",
  "checkout.promo_off": "MVR {amount} off",
  "checkout.ph_promo": "Enter promo code",
  "checkout.aria_promo": "Promo code",
  "checkout.loyalty_points": "Loyalty Points",
  "checkout.loyalty_available": "You have {n} pts available to use ({value} value).",
  "checkout.loyalty_held": "{held} pts are reserved on another order ({total} total balance).",
  "checkout.loyalty_min": "Minimum {n} available points required to redeem.",
  "checkout.loyalty_use": "Use {n} pts to save MVR {value} (max {pct}% of subtotal)",
  "checkout.loyalty_use_disabled": "Use loyalty points on this order",
  "checkout.friend_referral": "Friend's Referral Code",
  "checkout.friend_referral_hint": "Have a code from a friend? Enter it for a discount on your first order with that code.",
  "checkout.ph_referral": "Referral code",
  "checkout.aria_referral": "Friend referral code",
  "checkout.referral_est": "est. MVR {amount} off at checkout",
  "checkout.gift_card": "Gift Card",
  "checkout.ph_gift": "XXXX-XXXX-XXXX-XXXX",
  "checkout.aria_gift": "Gift card code",
  "checkout.gift_balance": "Available: MVR {amount} — click Apply to use it",
  "checkout.gift_balance_held": "Available: MVR {available} ({held} held on other orders) — click Apply to use it",

  "gift.hub_title": "Gift cards",
  "gift.hub_intro": "Buy a gift card for someone special, or check a code’s balance anytime.",
  "gift.hub_buy": "Buy a gift card",
  "gift.hub_buy_sub": "Pay online — we send the code to the recipient by SMS or email",
  "gift.history_title": "Your purchases",
  "gift.history_sub": "Gift cards you’ve bought — tap one to check delivery or resend to the recipient.",
  "gift.history_sign_in": "Sign in to see purchase history",
  "gift.history_empty": "No gift card purchases yet.",
  "gift.history_fail": "Could not load purchase history.",
  "gift.history_ready": "Ready",
  "gift.history_paid": "Paid — issuing",
  "gift.history_pending": "Awaiting payment",
  "gift.history_cancelled": "Cancelled",
  "gift.hub_balance": "Check balance",
  "gift.hub_balance_sub": "No sign-in needed. Enter the gift card code.",
  "gift.code_label": "Gift card code",
  "gift.code_ph": "Enter code",
  "gift.check_balance": "Check balance",
  "gift.checking": "Checking…",
  "gift.err_code": "Enter a gift card code.",
  "gift.err_balance": "Could not check that code. Try again.",
  "gift.balance_code": "Card {code}",
  "gift.balance_held": "MVR {amount} held on other orders",
  "gift.balance_expires": "Expires {date}",
  "gift.balance_hint": "Apply a gift card at checkout when you order.",
  "gift.open_account": "Open account →",
  "gift.title": "Buy a Gift Card",
  "gift.intro": "Pay online. We’ll send the code only to the recipient — by SMS and/or email.",
  "gift.sign_in": "Sign in to buy a gift card.",
  "gift.preview_brand": "Bake & Grill",
  "gift.preview_gift": "Gift card",
  "gift.preview_code_hint": "Code sent only to recipient",
  "gift.amount": "Choose amount",
  "gift.custom_ph": "Or enter custom (MVR 50–5000)",
  "gift.recipient_section": "Recipient",
  "gift.recipient_help": "Phone and/or email — only they see the gift code.",
  "gift.phone": "Phone",
  "gift.email": "Email",
  "gift.sender_section": "From",
  "gift.sender_named": "Show my name",
  "gift.sender_anon": "Anonymous",
  "gift.sender_name": "Name shown to recipient",
  "gift.sender_name_ph": "e.g. Aisha",
  "gift.send_anonymous": "Send anonymously (don’t show my name)",
  "gift.anonymous_help": "They’ll see “Anonymous gift” instead of your name.",
  "gift.err_sender": "Enter your name, or choose send anonymously.",
  "gift.err_contact": "Enter a recipient phone or email so we can send the code.",
  "gift.delivery_ok": "Gift code sent to {dest}. Only the recipient can see the full code.",
  "gift.delivery_partial": "Card issued. Delivery: {detail}. You can resend to the recipient below.",
  "gift.delivery_failed": "Card issued, but we could not deliver the code to the recipient. Resend below or contact the restaurant with order {order}.",
  "gift.buyer_masked": "Reference: {code}",
  "gift.code_private": "For privacy, the full gift code is only sent to the recipient — not shown here.",
  "gift.note": "Personal note (optional)",
  "gift.note_ph": "Happy birthday!",
  "gift.pay": "Pay MVR {amount}",
  "gift.paying": "Starting payment…",
  "gift.err_amount": "Enter an amount between MVR 50 and MVR 5000.",
  "gift.footnote": "Full code goes only to the recipient. You can resend for 48 hours after purchase.",
  "gift.back_account": "Back to account",
  "gift.back_hub": "Back to gift cards",
  "gift.success_title": "Gift Card",
  "gift.err_missing_order": "Missing purchase reference.",
  "gift.payment_not_confirmed": "Payment was not completed. You can try buying again.",
  "gift.issuing": "Confirming payment and issuing your gift card…",
  "gift.ready": "Gift card purchased",
  "gift.code_sent": "Full code sent to the recipient.",
  "gift.still_processing": "We’re still confirming your gift card.",
  "gift.still_processing_help": "Order {order}. If you were charged, tap Retry below — WhatsApp us with that order number if the recipient still doesn’t get the code.",
  "gift.payment_pending_title": "We’re still confirming your payment.",
  "gift.payment_pending_help": "Order {order}. Your bank may have charged you, but we haven’t recorded the payment yet. Tap Retry — we’ll check with the bank again. If it still fails, WhatsApp us with that order number.",
  "gift.issuing_pending_title": "Payment received — still issuing the card.",
  "gift.issuing_pending_help": "Order {order}. Tap Retry. WhatsApp us with that order number if the recipient still doesn’t get the code.",
  "gift.retry_status": "Retry / check again",
  "gift.view_orders": "View my orders",
  "gift.order_food": "Order food",
  "gift.buy_again": "Buy another gift card",
  "gift.resend_sms": "Resend SMS to recipient",
  "gift.resend_email": "Resend email to recipient",
  "gift.resend_both": "Resend SMS & email",
  "gift.resend_ok": "Resent to the recipient.",
  "gift.resend_fail": "Could not resend. Try again or contact the restaurant.",
  "gift.resend_window": "Resend to the recipient is available for 48 hours after purchase (up to 3 times).",
  "gift.whatsapp_help": "WhatsApp us about this order",
  "gift.copy_code": "Copy code",
  "gift.code_copied": "Code copied.",
  "gift.code_copy_fail": "Could not copy. Long-press the code to copy.",
  "gift.view_title": "Your Gift Card",
  "gift.view_invalid": "This gift card link is invalid or has expired.",
  "gift.view_hint": "Save this code. Redeem online at checkout, or show it at the counter for dine-in / takeaway.",
  "gift.view_code_label": "Gift card code",
  "gift.view_balance": "Available balance",
  "gift.view_redeem": "Order online & redeem",
  "gift.view_counter": "Or show this code at the counter",
  "gift.view_from": "{from}",
  "account.link_gift_cards": "Gift cards",
  "account.link_rewards": "Rewards",
  "checkout.share_referral": "Share your referral code with friends",
  "checkout.copy_code": "Copy code",
  "checkout.order_summary": "Order Summary",
  "checkout.loyalty_discount": "Loyalty discount",
  "checkout.loyalty_summary": "Loyalty",
  "checkout.gst": "GST",
  "checkout.delivery_fee": "Delivery fee",
  "checkout.total": "Total",
  "checkout.earn_pts": "You'll earn {n} pts from this order",
  "checkout.we_accept": "We accept",
  "checkout.card_brands_alt": "Amex, Visa, Mastercard, Maestro",
  "checkout.read_before": "Before completing your purchase, please read:",

  // ── Order tracking ──────────────────────────────────────────────────────────
  "track.page_title": "Order Status",
  "track.page_title_num": "Order #{n}",
  "track.live": "Live",
  "track.err_invalid_id": "Invalid order ID.",
  "track.err_need_link": "Open the full link from your SMS, or log in to view your order.",
  "track.err_pay_start": "Payment could not be started. Please try again in a moment.",
  "track.err_sign_in_pay": "Please sign in to pay for this order.",
  "track.err_amount": "Enter a valid amount in MVR.",
  "track.err_amount_max": "Amount cannot exceed MVR {amount} remaining.",
  "track.pay_ok_title": "Payment successful!",
  "track.pay_ok_sub": "Confirming your order — this page will update automatically.",
  "track.pay_fail_title": "Payment didn't go through",
  "track.pay_fail_sub_before": "Your card was not charged. Please try paying again — or",
  "track.pay_fail_sub_after": "and we'll sort it out.",
  "track.pay_fail_wa": "message us on WhatsApp",
  "track.pay_starting": "Starting payment…",
  "track.pay_again": "Pay again",
  "track.pay_mvr": "Pay MVR {amount}",
  "track.pay_part": "Pay part",
  "track.pay_custom_ph": "Custom amount (MVR)",
  "track.pay_remaining": "MVR {amount} remaining on this order.",
  "track.pay_pending": "Payment is still pending. Complete checkout to send your order to the kitchen.",
  "track.load_fail_title": "Couldn't load your order",
  "track.dismiss": "Dismiss",
  "track.order_hash": "Order #{n}",
  "track.details": "Order Details",
  "track.label_number": "Order number",
  "track.label_type": "Type",
  "track.label_status": "Status",
  "track.label_wait": "Kitchen wait",
  "track.label_pickup": "Pickup time",
  "track.label_paid_at": "Paid at",
  "track.wait_min": "~{n} min",
  "track.subtotal": "Subtotal",
  "track.promo": "Promo",
  "track.loyalty": "Loyalty",
  "track.gift_card": "Gift Card",
  "track.referral": "Referral",
  "track.delivery": "Delivery",
  "track.gst": "GST (8%)",
  "track.total": "Total",
  "track.delivery_address": "Delivery Address",
  "track.contact": "Contact: {name}",
  "track.items": "Items Ordered",
  "track.refresh_live": "Live tracking enabled — updates instantly",
  "track.refresh_poll": "Auto-refreshing every 10 seconds",
  "track.push_title": "Get notified when your order is ready",
  "track.push_sub": "We'll send you a push notification as your order progresses.",
  "track.push_enable": "Enable",
  "track.push_on": "Push notifications enabled — you'll be notified when your order status changes.",
  "track.help_title": "Need help with your order?",
  "track.help_sub": "We reply within 10 minutes on WhatsApp and Viber",
  "track.call": "Call",
  "track.call_aria": "Call us",
  "track.whatsapp": "WhatsApp",
  "track.wa_aria": "Contact us on WhatsApp",
  "track.viber": "Viber",
  "track.viber_aria": "Contact us on Viber",
  "track.directions": "Directions",
  "track.directions_aria": "Get directions",
  "track.share": "Share your order",
  "track.share_text": "Just ordered from Bake & Grill! Order #{n}",
  "track.share_referral": "Use my code {code} on your first order at Bake & Grill!",
  "track.share_copied": "Link copied to clipboard!",
  "track.reorder": "Order again",
  "track.reordering": "Adding to cart…",
  "track.back_menu": "← Back to menu",
  "track.back_menu_cta": "Back to menu",
  "track.payment_received": "Payment received!",
  "track.payment_received_sub": "Your order has been confirmed. Check your email or WhatsApp for details.",
  "track.not_found": "Order not found. Please sign in to view your order.",
  "track.footer_help": "Need help?",
  "track.footer_wa": "WhatsApp us",
  "track.footer_site": "← Back to main website",
  "track.points_title": "You earned {n} loyalty points!",
  "track.points_sub": "Points are added to your account — redeem them on your next order.",
  "track.step.received": "Received",
  "track.step.preparing": "Preparing",
  "track.step.ready": "Ready",
  "track.step.done": "Done",
  "track.type.dine_in": "Dine In",
  "track.type.takeaway": "Takeaway",
  "track.type.online_pickup": "Online Pickup",
  "track.type.delivery": "Delivery",
  "track.type.preorder": "Pre-order",
  "track.driver.title": "Your driver is on the way!",
  "track.driver.eta": "ETA ~{n} min",
  "track.driver.eta_estimate": "Rough estimate ~{n} min (not live traffic)",
  "track.proof_title": "Proof of delivery",
  "track.proof_view": "View delivery photo",
  "orders.type_pickup": "Pickup",
  "orders.type_dine_in": "Dine in",
  "orders.type_takeaway": "Takeaway",
  "orders.type_online_pickup": "Online pickup",
  "track.driver.last_seen": "Last seen: {n} min ago",
  "track.driver.last_unknown": "Unknown",
  "track.driver.loc_unavailable": "Location unavailable",
  "track.driver.locating": "Locating driver…",
  "track.driver.track_map": "Track on Map",
  "track.driver.call": "Call",
  "track.driver.whatsapp": "WhatsApp",
  "track.status.payment_pending.label": "Payment received!",
  "track.status.payment_pending.sub": "We're confirming your order — this usually takes under 30 seconds.",
  "track.status.payment_pending.next": "Your order will go to the kitchen as soon as it's confirmed",
  "track.status.pending.label": "Order confirmed!",
  "track.status.pending.sub": "Payment received. Your order is in the queue.",
  "track.status.pending.next": "Up next: kitchen will start preparing",
  "track.status.paid.label": "Order confirmed!",
  "track.status.paid.sub": "Payment received. The kitchen is being notified.",
  "track.status.paid.next": "Up next: kitchen will start preparing",
  "track.status.preparing.label": "Being prepared",
  "track.status.preparing.sub": "Your food is being freshly made right now.",
  "track.status.preparing.next": "Up next: ready for pickup or delivery",
  "track.status.in_progress.label": "Being prepared",
  "track.status.in_progress.sub": "Your order is in the kitchen right now.",
  "track.status.in_progress.next": "Up next: ready for pickup",
  "track.status.ready.label": "Ready!",
  "track.status.ready.sub": "Your order is ready.",
  "track.status.out_for_delivery.label": "Out for delivery",
  "track.status.out_for_delivery.sub": "Your order is on the way. Estimated: 15–30 min.",
  "track.status.picked_up.label": "Driver picked up your order",
  "track.status.picked_up.sub": "Your driver has collected your order and is heading your way!",
  "track.status.on_the_way.label": "Driver is on the way!",
  "track.status.on_the_way.sub": "Your order is almost there. Keep an eye out for your driver.",
  "track.status.delivered.label": "Delivered!",
  "track.status.delivered.sub": "Your order has been delivered. Enjoy your meal!",
  "track.status.completed.label": "Delivered!",
  "track.status.completed.sub": "Your order was delivered. Enjoy your meal!",
  "track.status.cancelled.label": "Order cancelled",
  "track.status.cancelled.sub": "This order was cancelled. If you were charged, your money will be refunded within 3–5 business days. Message us on WhatsApp if you need help.",

  // ── Reservations ────────────────────────────────────────────────────────────
  "reserve.page_title": "Table Reservation",
  "reserve.heading_form": "Make a Reservation",
  "reserve.heading_slots": "Select a Time Slot",
  "reserve.confirmed": "Reservation Confirmed!",
  "reserve.guests": "{n} guests",
  "reserve.table": "Table: {name}",
  "reserve.sms_soon": "You'll receive an SMS confirmation shortly.",
  "reserve.reference": "Reference: #{id}",
  "reserve.back_menu": "Back to Menu",
  "reserve.change_details": "← Change details",
  "reserve.no_slots": "No available slots for this date. Try another date.",
  "reserve.booking": "Booking…",
  "reserve.book_for": "Book for {slot}",
  "reserve.label_name": "Your Name",
  "reserve.ph_name": "Full name",
  "reserve.label_phone": "Phone Number",
  "reserve.ph_phone": "e.g. 7654321",
  "reserve.label_party": "Party Size",
  "reserve.party_dec": "Decrease party size",
  "reserve.party_inc": "Increase party size",
  "reserve.label_date": "Date",
  "reserve.label_notes": "Special Requests (optional)",
  "reserve.ph_notes": "Allergies, celebrations, seating preferences…",
  "reserve.checking": "Checking availability…",
  "reserve.check_cta": "Check Availability →",
  "reserve.err_slot": "Please select a time slot.",

  // ── Pre-order ───────────────────────────────────────────────────────────────
  "preorder.notice": "Pre-orders require at least 24 hours' notice. Our team will confirm your order by phone.",
  "preorder.step_items": "Choose Items",
  "preorder.step_details": "Event Details",
  "preorder.step_confirm": "Confirm",
  "preorder.search_ph": "Search items or categories…",
  "preorder.qty_remove": "Remove one",
  "preorder.qty_add": "Add one",
  "preorder.unavailable": "Unavailable",
  "preorder.items_selected": "{n} items selected",
  "preorder.item_selected": "1 item selected",
  "preorder.total_mvr": "MVR {amount} total",
  "preorder.next_details": "Next: Event Details →",
  "preorder.details_title": "Event Details",
  "preorder.label_fulfillment": "Fulfillment Date & Time *",
  "preorder.fulfillment_hint": "Must be at least 24 hours from now. We'll contact you to confirm.",
  "preorder.label_notes": "Special Instructions (optional)",
  "preorder.ph_notes": "Allergens, delivery location, setup notes…",
  "preorder.review_cta": "Review Order →",
  "preorder.review_title": "Review Your Pre-Order",
  "preorder.fulfillment_row": "Fulfillment",
  "preorder.notes_row": "Notes",
  "preorder.ordering_as": "Ordering as {name}",
  "preorder.submitting": "Submitting…",
  "preorder.whats_next": "What's Next?",
  "preorder.order_num": "Order {n}.",
  "preorder.browse_menu": "Browse Menu",
  "preorder.whatsapp_us": "WhatsApp Us",
  "preorder.fulfillment_done": "Fulfillment: {date}",
  "preorder.err_load": "Failed to load menu items.",
  "preorder.err_date": "Please select a valid fulfillment date and time.",
  "preorder.step1_default": "Our team will review your request within a few hours.",
  "preorder.step2_default": "We will call you to confirm availability and final details.",
  "preorder.step3_default": "Payment is collected on delivery or pickup day.",

  // ── Reviews ─────────────────────────────────────────────────────────────────
  "review.title": "Rate your order",
  "review.thanks": "Thanks for your feedback!",
  "review.ph_comment": "Share your experience (optional)…",
  "review.anonymous": "Post anonymously",
  "review.submit": "Submit Review",
  "review.submitting": "Submitting…",
  "review.err_rating": "Please select a rating.",
  "review.star_aria": "{n} star",

  // ── Hours / Contact / About chrome ──────────────────────────────────────────
  "hours.intro": "We're open most days — visit us at {address}.",
  "hours.checking": "Checking status…",
  "hours.open_now": "Open Now",
  "hours.closed_now": "Currently Closed",
  "hours.closed": "Closed",
  "hours.unavailable": "Hours not available",
  "hours.today": "Today",
  "hours.note_label": "Note:",
  "hours.order_now": "Order Now →",
  "hours.whatsapp": "WhatsApp Us",
  "hours.day.sunday": "Sunday",
  "hours.day.monday": "Monday",
  "hours.day.tuesday": "Tuesday",
  "hours.day.wednesday": "Wednesday",
  "hours.day.thursday": "Thursday",
  "hours.day.friday": "Friday",
  "hours.day.saturday": "Saturday",
  "contact.phone": "Phone",
  "contact.email": "Email",
  "contact.whatsapp": "WhatsApp",
  "contact.address": "Address",
  "contact.call_us": "Call us",
  "contact.send_email": "Send email",
  "contact.message_us": "Message us",
  "contact.visit_title": "Want to visit in person?",
  "contact.visit_sub": "Check our current opening hours before you head over.",
  "contact.see_hours": "See Hours →",
  "about.our_story": "Our Story",
  "about.visit_us": "Visit Us",
  "about.opening_hours": "Opening Hours",
  "about.contact_us": "Contact Us",
  "about.order_cta": "Browse Our Menu →",

  // ── Account panels ──────────────────────────────────────────────────────────
  "account.loading": "Loading…",
  "account.greeting_fallback": "there",
  "account.err_loyalty": "Failed to load loyalty account.",
  "account.err_reservations": "Failed to load reservations.",
  "account.err_favourites": "Failed to load favourites.",
  "account.err_preorders": "Failed to load pre-orders.",
  "account.err_reviews": "Failed to load reviews.",
  "account.err_referral": "Failed to load referral code.",
  "account.err_credit": "Failed to load credit account.",
  "account.err_deposit": "Failed to load deposit account.",
  "account.err_cancel_rsv": "Could not cancel reservation.",
  "account.err_submit_review": "Failed to submit review.",
  "account.err_credit_pref": "Failed to update reminder preference.",
  "account.rsv_title": "My Reservations",
  "account.rsv_empty": "No reservations yet.",
  "account.rsv_book": "Book a table →",
  "account.rsv_at": "at",
  "account.rsv_party": "Party of {n}",
  "account.cancelling": "Cancelling…",
  "account.cancel": "Cancel",
  "account.fav_title": "My Favourites",
  "account.fav_empty": "No favourites yet.",
  "account.fav_browse": "Browse the menu →",
  "account.fav_add_more": "Add more from the menu →",
  "account.unavailable": "Unavailable",
  "account.po_title": "My Pre-orders & Catering",
  "account.po_empty": "No pre-orders yet.",
  "account.po_place": "Place a pre-order →",
  "account.po_fallback": "Pre-order #{n}",
  "account.po_event": "Event: {name}",
  "account.po_ordered": "Ordered {date}",
  "account.rv_leave": "Leave a Review",
  "account.rv_waiting": "You have {n} completed order(s) waiting for a review.",
  "account.rv_cta": "Review",
  "account.rv_write": "Write a Review",
  "account.rv_rating": "Your Rating",
  "account.rv_comment": "Comment (optional)",
  "account.rv_ph": "Tell us about your experience…",
  "account.rv_anon": "Post anonymously",
  "account.rv_submitting": "Submitting…",
  "account.rv_submit": "Submit Review",
  "account.rv_mine": "My Reviews",
  "account.rv_empty": "No reviews yet.",
  "account.rv_posted_anon": "Posted anonymously",
  "account.rv_prev": "‹ Prev",
  "account.rv_next": "Next ›",
  "account.rv_page": "Page {n} of {m}",
  "account.loyalty_member": "{tier} Member",
  "account.loyalty_pts": "{n} pts",
  "account.loyalty_lifetime": "{n} lifetime points earned",
  "account.loyalty_top": "You've reached {tier} — the highest tier!",
  "account.loyalty_to_reach": "{n} pts to reach {tier}",
  "account.loyalty_earn_title": "How to Earn Points",
  "account.loyalty_earn_spend": "Every MVR 1 spent",
  "account.loyalty_earn_spend_d": "Earn 1 point on every order",
  "account.loyalty_earn_bday": "Birthday bonus",
  "account.loyalty_earn_bday_d": "Extra points on your birthday month",
  "account.loyalty_earn_ref": "Refer a friend",
  "account.loyalty_earn_ref_d": "Earn bonus points when friends join",
  "account.loyalty_redeem_title": "Redeeming Points",
  "account.loyalty_redeem_rate": "100 points = MVR 1",
  "account.loyalty_redeem_up_to": "You can redeem up to MVR {amount} on your next order!",
  "account.loyalty_empty": "Place your first order to start earning loyalty points.",
  "account.tier.bronze": "Bronze",
  "account.tier.silver": "Silver",
  "account.tier.gold": "Gold",
  "account.tier.platinum": "Platinum",
  "account.credit_none": "You do not have an approved credit account. Ask the restaurant if you need to pay on account.",
  "account.credit_title_status": "Credit Account · {status}",
  "account.credit_owed": "Balance owed",
  "account.credit_limit": "Credit limit",
  "account.credit_available": "Available",
  "account.credit_terms": "Payment terms: Net {n} days",
  "account.credit_due": "Next payment due: {date}",
  "account.credit_sms_title": "SMS Payment Reminders",
  "account.credit_sms_label": "Send SMS reminders before and on payment due dates",
  "account.credit_sms_hint": "Reminders are on by default. Turn off if you prefer email or in-app only.",
  "account.credit_invoices": "Open Invoices",
  "account.credit_invoices_empty": "No open invoices — your account is clear.",
  "account.credit_issued": "Issued {date}",
  "account.credit_on_account": "On credit account",
  "account.credit_order": "Order #{n}",
  "account.credit_overdue": "Overdue — {date}",
  "account.credit_due_short": "Due {date}",
  "account.credit_mvr_due": "MVR {amount} due",
  "account.credit_view": "View invoice →",
  "account.deposit_empty": "You do not have a prepaid deposit balance. Ask the restaurant if you would like to prepay for faster checkout in-store.",
  "account.deposit_title_status": "Deposit Balance · {status}",
  "account.deposit_balance": "Available balance",
  "account.deposit_instore": "In-store use",
  "account.deposit_available": "Available",
  "account.deposit_unavailable": "Unavailable",
  "account.deposit_status_note": "Your deposit account is {status}. Contact the restaurant for assistance.",
  "account.deposit_activity": "Recent Activity",
  "account.deposit_activity_empty": "No deposit transactions yet.",
  "account.deposit_bal": "Bal MVR {amount}",
  "account.ref_code_title": "Your Referral Code",
  "account.ref_copied": "✓ Copied!",
  "account.ref_copy": "📋 Copy Code",
  "account.ref_friends": "Friends joined",
  "account.ref_discount": "Discount per referral",
  "account.ref_how": "How Referrals Work",
  "account.ref_step1": "Share your code \"{code}\" with friends",
  "account.ref_step2": "They enter your code during checkout",
  "account.ref_step3": "They get MVR {amount} off their first order",
  "account.ref_step4": "You earn bonus loyalty points once they order",
  "account.ref_share_title": "Share Your Link",
  "account.ref_share_hint": "Send this link to friends — the referral code is pre-filled for them.",
  "account.ref_copy_short": "Copy",
  "account.ref_empty": "Place your first order to unlock your referral code.",
  "account.loyalty_redeem_blurb": "Apply your points at checkout to get a discount on your next order. Every {rate} off.",
  "account.privacy_updated": "Last updated: {date}",

  // Profile / addresses
  "account.profile_dob": "Date of birth",
  "account.profile_saving": "Saving…",
  "account.profile_save": "Save Changes",
  "account.profile_pw_title": "Change Password",
  "account.profile_pw_current": "Current Password",
  "account.profile_pw_new": "New Password",
  "account.profile_pw_confirm": "Confirm New Password",
  "account.profile_pw_changing": "Changing…",
  "account.profile_pw_cta": "Change Password",
  "account.addr_title": "Saved Delivery Addresses",
  "account.addr_default": "Default",
  "account.addr_fallback": "Address",
  "account.addr_edit": "Edit address",
  "account.addr_new": "New address",
  "account.addr_label": "Label",
  "account.addr_label_ph": "Home, Office…",
  "account.addr_line2": "Address line 2",
  "account.addr_maps": "Location link",
  "account.addr_maps_ph": "https://maps.google.com/…",
  "account.addr_contact_name": "Contact name *",
  "account.addr_contact_phone": "Contact phone *",
  "account.addr_notes": "Notes",
  "account.addr_saving": "Saving…",
  "account.addr_save": "Save address",
  "account.addr_err_load": "Failed to load addresses.",
  "account.addr_err_required": "Please fill in address, island, contact name, and phone.",
  "account.addr_ok_updated": "Address updated.",
  "account.addr_ok_saved": "Address saved.",
  "account.addr_err_save": "Could not save address.",
  "account.addr_confirm_delete": "Delete this address?",
  "account.addr_err_delete": "Could not delete address.",
  "account.addr_err_default": "Could not set default address.",
  "account.profile_err_load": "Failed to load profile.",
  "account.profile_ok": "Profile updated.",
  "account.profile_err_save": "Could not save changes.",
  "account.pw_err_all": "Please fill in all password fields.",
  "account.pw_err_mismatch": "New passwords do not match.",
  "account.pw_err_short": "New password must be at least 8 characters.",
  "account.pw_ok": "Password changed successfully.",
  "account.pw_err_change": "Could not change password. Check your current password.",
  "account.profile_phone": "Phone",
  "account.profile_name": "Name",
  "account.profile_name_ph": "Your name",
  "account.profile_email": "Email",
  "account.profile_email_ph": "you@example.com",
  "account.profile_dob_hint": "Optional — used for birthday loyalty rewards (SMS only if you haven't opted out).",
  "account.profile_loyalty_title": "Loyalty Points",
  "account.profile_loyalty_rate": "Earn 1 pt per MVR 1",
  "account.profile_member": "{tier} member",
  "account.profile_lifetime": "{n} lifetime",
  "account.addr_empty": "No saved addresses yet. Add one for faster checkout.",
  "account.addr_map": "Open map →",
  "account.addr_set_default": "Set default",
  "account.addr_edit_btn": "Edit",
  "account.addr_delete": "Delete",
  "account.addr_add": "Add address",
  "account.addr_line1": "Address *",
  "account.addr_island": "Island *",
  "account.addr_set_default_check": "Set as default address",
};


type LanguageContextType = {
  t: (key: string) => string;
  /** UI / card language — EN chrome copy; DV selects name_dv / short_description_dv on cards. */
  lang: 'en' | 'dv';
  setLang: (lang: 'en' | 'dv') => void;
};

const LanguageContext = createContext<LanguageContextType>({
  t: (k) => k,
  lang: 'en',
  setLang: () => {},
});

const LANG_STORAGE_KEY = "bakegrill_lang";

function readStoredLang(): 'en' | 'dv' {
  try {
    const v = localStorage.getItem(LANG_STORAGE_KEY);
    return v === 'dv' ? 'dv' : 'en';
  } catch {
    return 'en';
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<'en' | 'dv'>(() => readStoredLang());

  const setLang = (next: 'en' | 'dv') => {
    setLangState(next);
    try { localStorage.setItem(LANG_STORAGE_KEY, next); } catch { /* private mode / quota */ }
    document.documentElement.lang = next === 'dv' ? 'dv' : 'en';
    document.documentElement.dir = next === 'dv' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.lang = lang === 'dv' ? 'dv' : 'en';
    document.documentElement.dir = lang === 'dv' ? 'rtl' : 'ltr';
  }, [lang]);

  const t = translate;

  return (
    <LanguageContext.Provider value={{ t, lang, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

/** Lookup copy outside React hooks (e.g. class ErrorBoundary). */
export function translate(key: string): string {
  return TRANSLATIONS[key] ?? key;
}

export const useLanguage = () => useContext(LanguageContext);
