<?php

declare(strict_types=1);

/**
 * Content Studio registry — single source of editable marketing content blocks.
 * Built from docs/PER_APP_CONTENT_STUDIO_PLAN.md Appendix A.
 *
 * @return array<string, array<string, mixed>>
 */
return [
    'blocks' => [
        'about_page_story' => [
            'label' => 'About Page — Our Story',
            'group' => 'About',
            'type' => 'textarea',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'about_page_title' => [
            'label' => 'About Page — Title',
            'group' => 'About',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'About Bake & Grill',
        ],
        'about_values' => [
            'editor' => 'about_values',
            'label' => 'About Values',
            'group' => 'About',
            'type' => 'json',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'announcement_enabled' => [
            'label' => 'Show Announcement Banner',
            'group' => 'Everywhere',
            'type' => 'boolean',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|in:true,false,0,1',
            'default' => 'false',
        ],
        'announcement_style' => [
            'label' => 'Announcement — Style',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|in:info,warning,promo,alert|max:32',
            'default' => 'info',
            'description' => 'Visual style: info (blue), warning (amber), promo (green), or alert (red).',
        ],
        'announcement_text' => [
            'label' => 'Announcement — Text',
            'group' => 'Everywhere',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'announcement_url' => [
            'label' => 'Announcement — Link URL (optional)',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'business_address' => [
            'label' => 'Business Address',
            'group' => 'Everywhere',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Kalaafaanu Hingun, Malé',
            'description' => 'Full customer-facing address used on receipts and the shared business record.',
        ],
        'business_address_line1' => [
            'label' => 'Address line 1',
            'group' => 'Business Details',
            'type' => 'text',
            // Shared Business Details only — not Website/Order App Content Hub fields.
            'apps' => [],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Kalaafaanu Hingun',
            'description' => 'Street / road line for the shared business record.',
        ],
        'business_address_city' => [
            'label' => 'City / island',
            'group' => 'Business Details',
            'type' => 'text',
            'apps' => [],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Malé',
        ],
        'business_address_country' => [
            'label' => 'Country',
            'group' => 'Business Details',
            'type' => 'text',
            'apps' => [],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Maldives',
        ],
        'business_email' => [
            'label' => 'Business Email',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'hello@bakeandgrill.mv',
        ],
        'business_landmark' => [
            'label' => 'Landmark / Direction Hint',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Near H. Sahara',
        ],
        'business_maps_url' => [
            'label' => 'Google Maps URL',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'https://maps.google.com/?q=Kalaafaanu+Hingun+Male+Maldives',
        ],
        'business_phone' => [
            'label' => 'Business Phone',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '+960 912 0011',
        ],
        'business_hours' => [
            'label' => 'Business Hours (display)',
            'group' => 'Contact page',
            'type' => 'json',
            'editor' => 'business_hours',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:20000',
            'default' => null,
            'description' => 'Public hours card on the Website contact/maintenance pages. Operational schedule still uses business_hours_json.',
        ],
        'business_website' => [
            'label' => 'Business Website',
            'group' => 'Signage',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'https://bakeandgrill.mv',
        ],
        'business_viber' => [
            'label' => 'Viber Link',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'viber://chat?number=9609120011',
        ],
        'business_whatsapp' => [
            'label' => 'WhatsApp Link',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'https://wa.me/9609120011',
        ],
        'contact_email_label' => [
            'label' => 'Contact Page — Email Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Email',
        ],
        'contact_events_cta_headline' => [
            'label' => 'Contact Events Cta Headline',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Planning an event?',
        ],
        'contact_events_cta_text' => [
            'label' => 'Contact Events Cta Text',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Ask us about catering and trays for offices and celebrations.',
        ],
        'contact_hours_fallback' => [
            'label' => 'Contact Page — Hours Fallback Text',
            'group' => 'Contact page',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'contact_hours_heading' => [
            'label' => 'Contact Page — Hours Card Heading',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Opening Hours',
        ],
        'contact_location_heading' => [
            'label' => 'Contact Page — Location Card Heading',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Our Location',
        ],
        'contact_location_maps_label' => [
            'label' => 'Contact Page — Maps Link Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Open in Maps →',
        ],
        'contact_map_heading' => [
            'label' => 'Contact Page — Map Section Heading',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '📍 Find Us on the Map',
        ],
        'contact_meta_title' => [
            'label' => 'Contact Page — Browser Title',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Contact Us – Bake & Grill',
        ],
        'contact_page_eyebrow' => [
            'label' => 'Contact Page — Hero Eyebrow',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '📍 Find Us',
        ],
        'contact_page_subtitle' => [
            'label' => 'Contact Page — Hero Subtitle',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'contact_page_title' => [
            'label' => 'Contact Page — Hero Title',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Contact Us',
        ],
        'contact_phone_label' => [
            'label' => 'Contact Page — Phone Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Phone',
        ],
        'contact_schedule_label' => [
            'label' => 'Contact Page — Schedule Link Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Full Schedule →',
        ],
        'contact_touch_heading' => [
            'label' => 'Contact Page — Contact Card Heading',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Get in Touch',
        ],
        'contact_viber_label' => [
            'label' => 'Contact Page — Viber Button Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '📱 Viber',
        ],
        'contact_whatsapp_label' => [
            'label' => 'Contact Page — WhatsApp Button Label',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '💬 WhatsApp',
        ],
        'cta_band_headline' => [
            'label' => 'CTA Band — Headline',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Hungry? <em>Order now.</em>',
        ],
        'cta_band_subtext' => [
            'label' => 'CTA Band — Subtext',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Fresh from our kitchen to your door in 30–45 minutes. No fuss, no wait — just real food.',
        ],
        'delivery_threshold' => [
            'label' => 'Free Delivery Threshold',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'MVR 200',
            'description' => 'Read-only mirror of Ordering Control → Delivery → Free delivery from (MVR). Not editable in Content & Branding.',
        ],
        'delivery_time' => [
            'label' => 'Delivery Time Promise',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '30–45 min',
        ],
        'events_section_blurb' => [
            'label' => 'Events Section Blurb',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Trays and packages for offices, parties and celebrations.',
        ],
        'events_section_browse_cta' => [
            'label' => 'Events Section Browse Cta',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Browse catering',
        ],
        'events_section_headline' => [
            'label' => 'Events Section Headline',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Catering & Events',
        ],
        'events_section_plan_cta' => [
            'label' => 'Events Section Plan Cta',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Plan an event',
        ],
        'favicon' => [
            'label' => 'Favicon',
            'group' => 'Everywhere',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'dhivehi_font' => [
            'label' => 'Dhivehi font',
            'group' => 'Everywhere',
            'type' => 'font',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Thaana webfont for Dhivehi pages. Empty = shipped A_Faruma. Website and Order App each keep their own file.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'footer_contact_heading' => [
            'label' => 'Footer — Contact Heading',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Contact',
        ],
        'footer_links' => [
            'editor' => 'footer_links',
            'label' => 'Footer Links',
            'group' => 'Everywhere',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string',
            'default' => '[]',
            'description' => 'Legal / policy links in the compact mobile footer (Website + Order App).',
        ],
        'footer_location_heading' => [
            'label' => 'Footer — Location Heading',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Visit',
        ],
        'footer_quick_links_heading' => [
            'label' => 'Footer — Quick Links Heading',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Explore',
        ],
        'footer_rights_suffix' => [
            'label' => 'Footer — Rights Suffix',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'All rights reserved.',
        ],
        'footer_text' => [
            'label' => 'Footer blurb',
            'group' => 'Everywhere',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Short brand line under the logo. Copyright is built separately.',
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'footer_thanks' => [
            'label' => 'Footer thanks',
            'group' => 'Everywhere',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Thanks for choosing Bake & Grill — see you soon.',
        ],
        'footer_hours_heading' => [
            'label' => 'Footer — Hours Heading',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Opening Hours',
        ],
        'footer_payments_text' => [
            'label' => 'Footer — Payments line',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'BML · Cards · Cash · MVR',
        ],
        'footer_delivery_text' => [
            'label' => 'Footer — Delivery line',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Delivery across Malé & Hulhumalé',
        ],
        'footer_ramadan_note' => [
            'label' => 'Footer — Ramadan note',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Ramadan hours — open after Maghrib.',
        ],
        'show_social_links' => [
            'label' => 'Show social links',
            'group' => 'Everywhere',
            'type' => 'boolean',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|in:true,false,0,1',
            'default' => 'true',
        ],
        'social_instagram' => [
            'label' => 'Instagram URL',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'social_facebook' => [
            'label' => 'Facebook URL',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'social_tiktok' => [
            'label' => 'TikTok URL',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'hero_slides' => [
            'editor' => 'hero',
            'label' => 'Hero Slides',
            'group' => 'Home',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'description' => 'Images or muted video per slide. Dim overlay, Media Library picks, and image-as-poster for video uploads.',
            'validate' => 'nullable|string',
            'default' => '[]',
        ],
        // Deprecated — kept for read-fallback during transition; managed via hero_slides.
        'hero_slide_1' => [
            'label' => 'Hero Slide 1 (legacy)',
            'group' => 'Hero',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string',
            'default' => '{}',
            'deprecated' => true,
        ],
        'hero_slide_2' => [
            'label' => 'Hero Slide 2 (legacy)',
            'group' => 'Hero',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string',
            'default' => '{}',
            'deprecated' => true,
        ],
        'hero_slide_3' => [
            'label' => 'Hero Slide 3 (legacy)',
            'group' => 'Hero',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string',
            'default' => '{}',
            'deprecated' => true,
        ],
        'home_categories_eyebrow' => [
            'label' => 'Categories Section — Eyebrow',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'home_categories_subtitle' => [
            'label' => 'Categories Section — Subtitle',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Four things we do properly, every single day.',
        ],
        'home_categories_title' => [
            'label' => 'Categories Section — Title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Made for Malé',
        ],
        'home_closed_badge_text' => [
            'label' => 'Home — Closed Badge Text',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Closed now',
        ],
        'home_delivery_payment_line' => [
            'label' => 'Delivery Card — Payment Line',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'BML online payment or cash on delivery',
        ],
        'home_delivery_quality_line' => [
            'label' => 'Delivery Card — Quality Line',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Hot food at your door, not a cold box',
        ],
        'home_delivery_subtitle' => [
            'label' => 'Delivery Card — Subtitle',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'We come to you — no exceptions within the city',
        ],
        'home_delivery_tagline' => [
            'label' => 'Delivery Card — Tagline',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Delivery across all of Malé',
        ],
        'home_featured_eyebrow_bestseller' => [
            'label' => 'Featured Items — Eyebrow (has sales data)',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '🔥 Most Ordered',
        ],
        'home_featured_eyebrow_handpicked' => [
            'label' => 'Featured Items — Eyebrow (no sales data)',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '⭐ Handpicked',
        ],
        'home_featured_subtitle' => [
            'label' => 'Featured Items — Subtitle',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'The dishes our regulars order on repeat.',
        ],
        'home_featured_title_bestseller' => [
            'label' => 'Featured Items — Title (has sales data)',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Best Sellers',
        ],
        'home_featured_title_handpicked' => [
            'label' => 'Featured Items — Title (no sales data)',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Featured Items',
        ],
        'home_hero_fallback_subtitle' => [
            'label' => 'Hero Fallback — Subtitle',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Where Dhivehi breakfast meets artisan baking. Real food. Proper char. Baked fresh every morning at 5am.',
        ],
        'home_hero_fallback_title' => [
            'label' => 'Hero Fallback — Title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'home_location_eyebrow' => [
            'label' => 'Location Section — Eyebrow',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Find us',
        ],
        'home_location_subtitle' => [
            'label' => 'Location Section — Subtitle',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'home_location_title' => [
            'label' => 'Location Section — Title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Visit or Order',
        ],
        'home_open_badge_text' => [
            'label' => 'Home — Open Badge Text',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'home_proof_eyebrow' => [
            'label' => 'Social Proof — Eyebrow',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Loved by Malé',
        ],
        // Retired in Stage F — home arrangement lives in page_blocks (see
        // App\Domains\Content\Blocks\LegacyHomeLayout). Existing site_settings
        // rows are still read by HomeLayoutMigrator for un-migrated installs.
        // 'home_section_order' => …
        'home_specials_eyebrow' => [
            'label' => 'Specials eyebrow',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Limited time',
        ],
        'home_specials_title' => [
            'label' => 'Specials title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'offers_headline' => [
            'label' => 'Offers rail headline',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Offers',
        ],
        'offers_subtext' => [
            'label' => 'Offers rail subtext',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Specials and promos running right now.',
        ],
        'homepage_categories' => [
            'editor' => 'categories',
            'label' => 'Hedhikaa',
            'group' => 'Home',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'hours_call_confirm_label' => [
            'label' => 'Hours Page — Footer "Call to confirm" prefix',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Call us to confirm:',
        ],
        'hours_closed_status_text' => [
            'label' => 'Hours Page — Closed Status Badge',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '● Currently closed',
        ],
        'hours_contact_page_label' => [
            'label' => 'Hours Page — Footer contact-page link label',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Contact page \\xe2\\x86\\x92',
        ],
        'hours_meta_description' => [
            'label' => 'Hours Page — Meta Description',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'See our opening hours. Bake & Grill is open 7 days a week in Mal\\xc3\\xa9, Maldives.',
        ],
        'hours_meta_title' => [
            'label' => 'Hours Page — Browser Title',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Opening Hours \\xe2\\x80\\x93 Bake & Grill',
        ],
        'hours_open_status_text' => [
            'label' => 'Hours Page — Open Status Badge',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'hours_order_btn_label' => [
            'label' => 'Hours Page — CTA Button Label',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '\\xf0\\x9f\\x9b\\x92 Order Online Now',
        ],
        'hours_page_cta_subtitle' => [
            'label' => 'Hours Page — CTA Subtitle',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Place your order online and have it delivered fresh to your door',
        ],
        'hours_page_cta_title' => [
            'label' => 'Hours Page — CTA Title',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Ready to order?',
        ],
        'hours_page_eyebrow' => [
            'label' => 'Hours Page — Hero Eyebrow',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '🕐 Schedule',
        ],
        'hours_page_note' => [
            'label' => 'Hours Page — Holiday Note',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Hours may vary on public holidays.',
        ],
        'hours_page_title' => [
            'label' => 'Hours Page — Hero Title',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Opening Hours',
        ],
        'hours_special_closure_label' => [
            'label' => 'Hours Page — Special Closure Prefix',
            'group' => 'Hours page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Special Closure:',
        ],
        'legal_privacy_body' => [
            'label' => 'Privacy Policy — Body Override (plain text)',
            'group' => 'Legal',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'legal_refund_body' => [
            'label' => 'Refund Policy — Body Override (plain text)',
            'group' => 'Legal',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'legal_terms_body' => [
            'label' => 'Terms & Conditions — Body Override (plain text)',
            'group' => 'Legal',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'logo' => [
            'label' => 'Logo (Light)',
            'group' => 'Everywhere',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'logo_dark' => [
            'label' => 'Logo (Dark)',
            'group' => 'Everywhere',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'default_item_image' => [
            'label' => 'Default item photo',
            'group' => 'Home',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Shown for menu items that don\'t have their own photo.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'menu_new_days' => [
            'label' => 'New items window (days)',
            'group' => 'Menu',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Items created within this many days appear under “New items” on the dine-in menu.',
            'validate' => 'nullable|integer|min:1|max:365',
            'default' => '30',
        ],
        'maps_embed_url' => [
            'label' => 'Google Maps embed URL',
            'group' => 'Contact page',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
            'description' => 'Optional iframe embed URL for the contact map (shared business record).',
        ],
        'menu_page_title' => [
            'label' => 'Menu Page — Title',
            'group' => 'Menu',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Our Complete Menu',
        ],
        'meta_description' => [
            'label' => 'Meta Description',
            'group' => 'Everywhere',
            'type' => 'textarea',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Your neighborhood cafe serving freshly baked goods and fire-grilled favorites in Malé, Maldives.',
        ],
        'meta_title' => [
            'label' => 'Meta Title',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Bake & Grill — Fresh Baked, Fire Grilled',
        ],
        'nav_order_cta_text' => [
            'label' => 'Nav — Order CTA Button',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Order Now →',
        ],
        'office_orders_enabled' => [
            'label' => 'Office Orders Enabled',
            'group' => 'Home',
            'type' => 'boolean',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|in:true,false,0,1',
            'default' => 'true',
        ],
        'office_orders_headline' => [
            'label' => 'Office Orders Headline',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Office orders',
        ],
        'office_orders_subtext' => [
            'label' => 'Office Orders Subtext',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Feed the team — trays and packages for the office.',
        ],
        'og_image' => [
            'label' => 'Link preview image',
            'group' => 'Everywhere',
            'type' => 'image',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Shown when someone shares a link on WhatsApp, Facebook, or iMessage.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'order_auth_privacy_line' => [
            'label' => 'Login — Privacy Line',
            'group' => 'Ordering',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Your number is used only for order updates. No spam.',
        ],
        'order_checkout_subtitle' => [
            'label' => 'Checkout — Subtitle',
            'group' => 'Ordering',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Secure payment · Straight to the kitchen',
        ],
        'order_checkout_title' => [
            'label' => 'Checkout — Title',
            'group' => 'Ordering',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Complete your order',
        ],
        'order_home_reviews_title' => [
            'label' => 'Order home reviews title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'What guests say',
        ],
        'order_home_greeting_hello' => [
            'label' => 'Home greeting — Hello',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'description' => 'Welcome line when the customer has no profile name (or is signed out).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Hello',
        ],
        'order_home_greeting_named' => [
            'label' => 'Home greeting — with name',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'description' => 'Welcome line when a profile name is set. Use {name} for the customer’s name.',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Hello, {name}',
        ],
        'order_home_greeting_sub' => [
            'label' => 'Home greeting — subtitle',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'description' => 'Short line under the Hello greeting on the order-app home.',
            'validate' => 'nullable|string|max:5000',
            'default' => 'What would you like today?',
        ],
        'order_mode_delivery_hint' => [
            'label' => 'Delivery mode hint',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Hint under the Delivery mode card.',
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'order_mode_pickup_hint' => [
            'label' => 'Pickup mode hint',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Hint under the Pickup mode card.',
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],
        'order_mode_dine_in_hint' => [
            'label' => 'Eat here mode hint',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Hint under the Eat here mode card.',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Order and pay online — your table is held for you and food is ready when you arrive.',
        ],
        'order_mode_delivery_image' => [
            'label' => 'Delivery mode card photo',
            'group' => 'Home',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Photo on the Delivery card. Website and Order App each keep their own image.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'order_mode_pickup_image' => [
            'label' => 'Pickup mode card photo',
            'group' => 'Home',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Photo on the Pickup card. Website and Order App each keep their own image.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'order_mode_dine_in_image' => [
            'label' => 'Eat here mode card photo',
            'group' => 'Home',
            'type' => 'image',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Photo on the Eat here card. Website and Order App each keep their own image.',
            'validate' => 'nullable|string|max:2048',
            'default' => '',
        ],
        'order_mode_delivery_info' => [
            'label' => 'Delivery — info sheet',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Explanation shown when someone taps Delivery (especially when it is closed).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'We bring your order to your door. Choose your address at checkout and track it on the way.',
        ],
        'order_mode_pickup_info' => [
            'label' => 'Pickup — info sheet',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Explanation shown when someone taps Pickup (especially when it is closed).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Order online, then collect from our shop when it is ready. No need to wait in a queue to order.',
        ],
        'order_mode_dine_in_info' => [
            'label' => 'Eat here — info sheet',
            'group' => 'Home',
            'type' => 'textarea',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Explanation shown when someone taps Eat here (especially when it is closed).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Order and pay online, and your table is held for you. Food is ready when you arrive.',
        ],
        'order_mode_status_available' => [
            'label' => 'Mode status — available',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Status line when a fulfilment mode is available right now.',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Available now',
        ],
        'order_mode_status_unavailable' => [
            'label' => 'Mode status — unavailable',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Status line when a mode is off (and no reopening time is known).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Unavailable right now',
        ],
        'order_mode_status_unavailable_opens' => [
            'label' => 'Mode status — closed until',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Status when a mode is closed by hours. Use {time} for the next opening time.',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Closed until {time}',
        ],
        'order_mode_learn_more' => [
            'label' => 'Mode card — Learn more',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'description' => 'Link text on a closed mode card (opens the info sheet).',
            'validate' => 'nullable|string|max:5000',
            'default' => 'Learn more',
        ],
        'order_payment_compliance' => [
            'label' => 'Checkout — Payment Compliance Text',
            'group' => 'Ordering',
            'type' => 'textarea',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => true,
            'validate' => 'nullable|string|max:5000',
            'default' => 'All prices in MVR. Payments are processed securely via Bank of Maldives (BML). Your card details are never stored on our servers.',
        ],
        'order_hours_closed' => [
            'label' => 'Hours badge — Closed',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Online ordering closed',
        ],
        'order_hours_closed_opens' => [
            'label' => 'Hours badge — Closed · Opens {time}',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Online ordering closed · Opens {time}',
        ],
        'order_hours_open' => [
            'label' => 'Hours badge — Open',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Online ordering open',
        ],
        'order_hours_open_closes' => [
            'label' => 'Hours badge — Open · Closes {time}',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['order_app'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Online ordering open · Closes {time}',
        ],
        // Retired (inert site_settings rows may remain): order_status_* menu banners,
        // menu_page_subtitle, unused preorder_* copy, office_orders_min_guests.
        // Live badges use order_hours_*; do not re-seed dead keys.

        'primary_color' => [
            'label' => 'Primary Color',
            'group' => 'Everywhere',
            'type' => 'color',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:32',
            // Empty default: unset means "use hardcoded CSS palette" (non-breaking).
            'default' => '',
        ],
        'privacy_address_label' => [
            'label' => 'Privacy Page — Address Label in Contact block',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Address:',
        ],
        'privacy_email' => [
            'label' => 'Privacy Page — Privacy Contact Email',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'privacy@bakeandgrill.mv',
        ],
        'privacy_email_label' => [
            'label' => 'Privacy Page — Email Label in Contact block',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Email:',
        ],
        'privacy_last_updated_label' => [
            'label' => 'Privacy Page — "Last updated" prefix',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Last updated:',
        ],
        'privacy_meta_title' => [
            'label' => 'Privacy Page — Browser Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Privacy Policy - Bake & Grill',
        ],
        'privacy_page_title' => [
            'label' => 'Privacy Page — Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Privacy Policy',
        ],
        'privacy_phone_label' => [
            'label' => 'Privacy Page — Phone Label in Contact block',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Phone:',
        ],
        // Website-only: the order app parses this key but renders nothing from
        // it, so offering it as shared content was misleading.
        'proof_details' => [
            'editor' => 'proof',
            'label' => 'Baking starts',
            'group' => 'Home',
            'type' => 'json',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '5am',
        ],
        'proof_label' => [
            'label' => 'Social Proof — Label',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'orders delivered in Malé every week — and counting.',
        ],
        'proof_stat' => [
            'label' => 'Social Proof — Main Stat',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '500+',
        ],
        'refund_last_updated_label' => [
            'label' => 'Refund Page — "Last updated" prefix',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Last updated:',
        ],
        'refund_meta_title' => [
            'label' => 'Refund Page — Browser Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Refund & Cancellation Policy - Bake & Grill',
        ],
        'refund_page_subtitle' => [
            'label' => 'Refund Page — Subtitle',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Please read this policy before completing your purchase.',
        ],
        'refund_page_title' => [
            'label' => 'Refund Page — Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Refund & Cancellation Policy',
        ],
        // Retired in Stage F — section visibility lives in page_blocks
        // (is_enabled per block). The old section_*_enabled site_settings
        // rows are still read by HomeLayoutMigrator for un-migrated installs.
        // 'section_hero_enabled', 'section_specials_enabled',
        // 'section_featured_enabled', 'section_categories_enabled',
        // 'section_proof_enabled', 'section_cta_enabled',
        // 'section_location_enabled', 'section_reviews_enabled' => …
        'language_switcher_enabled' => [
            'label' => 'Show language switcher (EN / ދވ)',
            'group' => 'Everywhere',
            'type' => 'boolean',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|in:true,false,0,1',
            'default' => 'false',
        ],
        'site_name' => [
            'label' => 'Site Name',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Bake & Grill',
        ],
        'site_tagline' => [
            'label' => 'Tagline',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Fresh Baked, Fire Grilled',
        ],
        'terms_email_label' => [
            'label' => 'Terms Page — Email Label in Corporate Box',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Email:',
        ],
        'terms_last_updated_label' => [
            'label' => 'Terms Page — "Last updated" prefix',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Last updated:',
        ],
        'terms_meta_title' => [
            'label' => 'Terms Page — Browser Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Terms & Conditions - Bake & Grill',
        ],
        'terms_page_corporate_service_text' => [
            'label' => 'Terms Page — Corporate Box Service Line',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Customer service: Available via WhatsApp, Viber, or the contact details above.',
        ],
        'terms_page_subtitle' => [
            'label' => 'Terms Page — Subtitle',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Please read these terms before completing your purchase.',
        ],
        'terms_page_title' => [
            'label' => 'Terms Page — Title',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Terms & Conditions',
        ],
        'terms_phone_label' => [
            'label' => 'Terms Page — Phone Label in Corporate Box',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => 'Phone:',
        ],
        'trust_items' => [
            'editor' => 'trust',
            'label' => 'Trust Items',
            'group' => 'Home',
            'type' => 'json',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:5000',
            'default' => '',
        ],

        // ── Location / visit CTAs (Website home location block) ───────────────
        'home_chat_label' => [
            'label' => 'Home — Chat label',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:120',
            'default' => 'Chat with us',
            'description' => 'Label for the chat action on Website home / Order App brand footer.',
        ],
        'home_visit_card_title' => [
            'label' => 'Home — Visit card title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:200',
            'default' => 'Visit us',
        ],
        'home_delivery_card_title' => [
            'label' => 'Home — Delivery card title',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:200',
            'default' => 'Delivery',
        ],
        'home_directions_cta' => [
            'label' => 'Home — Directions CTA',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:120',
            'default' => 'Get directions',
        ],
        'home_call_cta' => [
            'label' => 'Home — Call CTA',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:120',
            'default' => 'Call us',
        ],
        'home_order_via_app_label' => [
            'label' => 'Home — Order via app label',
            'group' => 'Home',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:120',
            'default' => 'Order via app',
        ],
        'legal_last_updated_date' => [
            'label' => 'Legal — Last updated date',
            'group' => 'Legal',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:80',
            'default' => '',
            'description' => 'Shown on Website legal pages (privacy / terms / refunds).',
        ],
        'meta_keywords' => [
            'label' => 'SEO — Meta keywords',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website'],
            'shareable' => false,
            'public' => false,
            'rich' => false,
            'validate' => 'nullable|string|max:1000',
            'default' => '',
        ],
        'google_analytics_id' => [
            'label' => 'Google Analytics ID',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:40',
            'default' => '',
            'description' => 'Measurement ID (G-…) for Website and Order App analytics.',
        ],
        'google_tag_manager_id' => [
            'label' => 'Google Tag Manager ID',
            'group' => 'Everywhere',
            'type' => 'text',
            'apps' => ['website', 'order_app'],
            'shareable' => true,
            'public' => true,
            'rich' => false,
            'validate' => 'nullable|string|max:40',
            'default' => '',
            'description' => 'Container ID (GTM-…) for Website and Order App.',
        ],
    ],
];
