/** Auto-derived Stage 4 hub groups from docs/content_surface_inventory.json — do not hand-edit keys. */
import type { ContentApp } from '../../api/content';

export const WEBSITE_HUB_GROUP_BY_KEY: Record<string, string> = {
  "announcement_enabled": "Everywhere",
  "announcement_style": "Everywhere",
  "announcement_text": "Everywhere",
  "announcement_url": "Everywhere",
  "business_address": "Everywhere",
  "business_email": "Everywhere",
  "business_hours": "Contact page",
  "business_landmark": "Everywhere",
  "business_maps_url": "Everywhere",
  "business_phone": "Everywhere",
  "business_viber": "Everywhere",
  "business_website": "Everywhere",
  "business_whatsapp": "Everywhere",
  "contact_email_label": "Contact page",
  "contact_events_cta_headline": "Contact page",
  "contact_events_cta_text": "Contact page",
  "contact_hours_fallback": "Contact page",
  "contact_hours_heading": "Contact page",
  "contact_location_heading": "Contact page",
  "contact_location_maps_label": "Contact page",
  "contact_map_heading": "Contact page",
  "contact_meta_title": "Contact page",
  "contact_page_eyebrow": "Contact page",
  "contact_page_subtitle": "Contact page",
  "contact_page_title": "Contact page",
  "contact_phone_label": "Contact page",
  "contact_schedule_label": "Contact page",
  "contact_touch_heading": "Contact page",
  "contact_viber_label": "Contact page",
  "contact_whatsapp_label": "Contact page",
  "cta_band_headline": "Home",
  "cta_band_subtext": "Home",
  "default_item_image": "Home",
  "delivery_threshold": "Home",
  "delivery_time": "Home",
  "events_section_blurb": "Home",
  "events_section_browse_cta": "Home",
  "events_section_headline": "Home",
  "events_section_plan_cta": "Home",
  "favicon": "Everywhere",
  "footer_contact_heading": "Everywhere",
  "footer_delivery_text": "Everywhere",
  "footer_hours_heading": "Everywhere",
  "footer_links": "Everywhere",
  "footer_location_heading": "Everywhere",
  "footer_payments_text": "Everywhere",
  "footer_quick_links_heading": "Everywhere",
  "footer_ramadan_note": "Everywhere",
  "footer_rights_suffix": "Everywhere",
  "footer_text": "Everywhere",
  "footer_thanks": "Everywhere",
  "google_analytics_id": "Everywhere",
  "google_tag_manager_id": "Everywhere",
  "hero_slides": "Home",
  "home_call_cta": "Home",
  "home_categories_eyebrow": "Home",
  "home_categories_subtitle": "Home",
  "home_categories_title": "Home",
  "home_chat_label": "Everywhere",
  "home_closed_badge_text": "Home",
  "home_delivery_card_title": "Home",
  "home_delivery_payment_line": "Home",
  "home_delivery_quality_line": "Home",
  "home_delivery_subtitle": "Home",
  "home_delivery_tagline": "Home",
  "home_directions_cta": "Home",
  "home_featured_eyebrow_bestseller": "Home",
  "home_featured_eyebrow_handpicked": "Home",
  "home_featured_subtitle": "Home",
  "home_featured_title_bestseller": "Home",
  "home_featured_title_handpicked": "Home",
  "home_location_eyebrow": "Home",
  "home_location_subtitle": "Home",
  "home_location_title": "Home",
  "home_open_badge_text": "Home",
  "home_order_via_app_label": "Home",
  "home_proof_eyebrow": "Home",
  "home_specials_eyebrow": "Home",
  "home_specials_title": "Home",
  "home_visit_card_title": "Home",
  "homepage_categories": "Home",
  "hours_call_confirm_label": "Hours page",
  "hours_closed_status_text": "Hours page",
  "hours_contact_page_label": "Hours page",
  "hours_meta_description": "Hours page",
  "hours_meta_title": "Hours page",
  "hours_open_status_text": "Hours page",
  "hours_order_btn_label": "Hours page",
  "hours_page_cta_subtitle": "Hours page",
  "hours_page_cta_title": "Hours page",
  "hours_page_eyebrow": "Hours page",
  "hours_page_note": "Hours page",
  "hours_page_title": "Hours page",
  "hours_special_closure_label": "Hours page",
  "language_switcher_enabled": "Everywhere",
  "legal_last_updated_date": "Legal",
  "legal_privacy_body": "Legal",
  "legal_refund_body": "Legal",
  "legal_terms_body": "Legal",
  "logo": "Everywhere",
  "logo_dark": "Everywhere",
  "maps_embed_url": "Contact page",
  "menu_new_days": "Everywhere",
  "meta_description": "Everywhere",
  "meta_keywords": "Everywhere",
  "meta_title": "Everywhere",
  "nav_order_cta_text": "Everywhere",
  "offers_headline": "Home",
  "offers_subtext": "Home",
  "og_image": "Everywhere",
  "order_mode_delivery_hint": "Home",
  "order_mode_delivery_info": "Home",
  "order_mode_dine_in_hint": "Home",
  "order_mode_dine_in_info": "Home",
  "order_mode_learn_more": "Home",
  "order_mode_pickup_hint": "Home",
  "order_mode_pickup_info": "Home",
  "order_mode_status_available": "Home",
  "order_mode_status_unavailable": "Home",
  "order_mode_status_unavailable_opens": "Home",
  "primary_color": "Everywhere",
  "privacy_address_label": "Legal",
  "privacy_email": "Legal",
  "privacy_email_label": "Legal",
  "privacy_last_updated_label": "Legal",
  "privacy_meta_title": "Legal",
  "privacy_page_title": "Legal",
  "privacy_phone_label": "Legal",
  "proof_details": "Home",
  "proof_label": "Home",
  "proof_stat": "Home",
  "refund_last_updated_label": "Legal",
  "refund_meta_title": "Legal",
  "refund_page_subtitle": "Legal",
  "refund_page_title": "Legal",
  "show_social_links": "Everywhere",
  "site_name": "Everywhere",
  "site_tagline": "Everywhere",
  "social_facebook": "Everywhere",
  "social_instagram": "Everywhere",
  "social_tiktok": "Everywhere",
  "terms_email_label": "Legal",
  "terms_last_updated_label": "Legal",
  "terms_meta_title": "Legal",
  "terms_page_corporate_service_text": "Legal",
  "terms_page_subtitle": "Legal",
  "terms_page_title": "Legal",
  "terms_phone_label": "Legal",
  "trust_items": "Home",
};

export const ORDER_APP_HUB_GROUP_BY_KEY: Record<string, string> = {
  "about_page_story": "About",
  "about_page_title": "About",
  "about_values": "About",
  "announcement_enabled": "Everywhere",
  "announcement_style": "Everywhere",
  "announcement_text": "Everywhere",
  "announcement_url": "Everywhere",
  "business_address": "Everywhere",
  "business_email": "Everywhere",
  "business_landmark": "Everywhere",
  "business_maps_url": "Everywhere",
  "business_phone": "Everywhere",
  "business_viber": "Everywhere",
  "business_website": "Signage",
  "business_whatsapp": "Everywhere",
  "contact_page_subtitle": "Contact page",
  "contact_page_title": "Contact page",
  "default_item_image": "Menu",
  "delivery_threshold": "Home",
  "delivery_time": "Home",
  "favicon": "Everywhere",
  "footer_contact_heading": "Everywhere",
  "footer_delivery_text": "Everywhere",
  "footer_hours_heading": "Everywhere",
  "footer_links": "Everywhere",
  "footer_location_heading": "Everywhere",
  "footer_payments_text": "Everywhere",
  "footer_quick_links_heading": "Everywhere",
  "footer_rights_suffix": "Everywhere",
  "footer_text": "Everywhere",
  "footer_thanks": "Everywhere",
  "google_analytics_id": "Everywhere",
  "google_tag_manager_id": "Everywhere",
  "hero_slides": "Home",
  "home_categories_eyebrow": "Home",
  "home_categories_title": "Home",
  "home_chat_label": "Everywhere",
  "home_delivery_tagline": "Home",
  "home_hero_fallback_subtitle": "Home",
  "home_hero_fallback_title": "Home",
  "home_proof_eyebrow": "Home",
  "home_specials_eyebrow": "Home",
  "home_specials_title": "Home",
  "homepage_categories": "Home",
  "hours_page_title": "Hours page",
  "language_switcher_enabled": "Everywhere",
  "legal_privacy_body": "Privacy",
  "logo": "Everywhere",
  "logo_dark": "Everywhere",
  "menu_new_days": "Menu",
  "menu_page_title": "Menu",
  "nav_order_cta_text": "Everywhere",
  "offers_headline": "Home",
  "offers_subtext": "Home",
  "office_orders_enabled": "Home",
  "office_orders_headline": "Home",
  "office_orders_subtext": "Home",
  "order_auth_privacy_line": "Ordering",
  "order_checkout_subtitle": "Ordering",
  "order_checkout_title": "Ordering",
  "order_home_greeting_hello": "Home",
  "order_home_greeting_named": "Home",
  "order_home_greeting_sub": "Home",
  "order_home_reviews_title": "Home",
  "order_hours_closed": "Home",
  "order_hours_closed_opens": "Home",
  "order_hours_open": "Home",
  "order_hours_open_closes": "Home",
  "order_mode_delivery_hint": "Home",
  "order_mode_delivery_info": "Home",
  "order_mode_dine_in_hint": "Home",
  "order_mode_dine_in_info": "Home",
  "order_mode_learn_more": "Home",
  "order_mode_pickup_hint": "Home",
  "order_mode_pickup_info": "Home",
  "order_mode_status_available": "Home",
  "order_mode_status_unavailable": "Home",
  "order_mode_status_unavailable_opens": "Home",
  "order_payment_compliance": "Ordering",
  "primary_color": "Everywhere",
  "privacy_page_title": "Privacy",
  "show_social_links": "Everywhere",
  "site_name": "Everywhere",
  "site_tagline": "Everywhere",
  "social_facebook": "Everywhere",
  "social_instagram": "Everywhere",
  "social_tiktok": "Everywhere",
  "trust_items": "Home",
};

export const WEBSITE_HUB_SECTION_ORDER = [
  'Home',
  'Menu page',
  'Contact page',
  'Hours page',
  'Legal',
  'Everywhere',
] as const;

export const ORDER_APP_HUB_SECTION_ORDER = [
  'Home',
  'Menu',
  'Ordering',
  'Order history',
  'Gift cards',
  'About',
  'Contact page',
  'Hours page',
  'Privacy',
  'Signage',
  'Everywhere',
] as const;

export function hubGroupForKey(key: string, app: ContentApp): string | null {
  const map = app === 'order_app' ? ORDER_APP_HUB_GROUP_BY_KEY : WEBSITE_HUB_GROUP_BY_KEY;
  return map[key] ?? null;
}

