export type Pane =
  | "sales"
  | "receipts"
  | "shift"
  | "open_tickets"
  | "events"
  | "shift_history"
  | "sales_report"
  | "ops"
  | "expenses"
  | "my_requests"
  | "buying_list"
  | "kitchen_receiving"
  | "wholesale_dispatch"
  | "wholesale_reconcile";
