// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const POS_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-10-06-235236-f29518e",
  "commit": "f29518e",
  "built_at": "2026-10-06T23:52:36.872Z"
} as const;
