// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const POS_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-08-31-190341-c736c5e13",
  "commit": "c736c5e13",
  "built_at": "2026-08-31T19:03:41.172Z"
} as const;
