// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const POS_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-05-22-181859-8aaf25b5",
  "commit": "8aaf25b5",
  "built_at": "2026-05-22T18:18:59.151Z"
} as const;
