#!/usr/bin/env node
/**
 * Writes public/admin-version.json and src/adminBuildInfo.ts before each
 * dev/build so the running bundle knows its own build id — the same stamp the
 * POS carries, so the admin can tell when a newer build is on the server.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));

let commit = "dev";
try {
  commit = execSync("git rev-parse --short HEAD", {
    cwd: path.join(root, "../.."),
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"],
  }).trim();
} catch {
  // offline / shallow clone — keep "dev"
}

const now = new Date();
const pad = (n) => String(n).padStart(2, "0");
const datePart = `${now.getUTCFullYear()}-${pad(now.getUTCMonth() + 1)}-${pad(now.getUTCDate())}`;
const timePart = `${pad(now.getUTCHours())}${pad(now.getUTCMinutes())}${pad(now.getUTCSeconds())}`;
const build = `${datePart}-${timePart}-${commit}`;

const info = {
  version: pkg.version,
  build,
  commit,
  built_at: now.toISOString(),
};

const json = `${JSON.stringify(info, null, 2)}\n`;

mkdirSync(path.join(root, "public"), { recursive: true });
writeFileSync(path.join(root, "public", "admin-version.json"), json);

writeFileSync(
  path.join(root, "src", "adminBuildInfo.ts"),
  `// Auto-generated by scripts/generate-version.mjs — do not edit manually.\nexport const ADMIN_BUILD_INFO = ${JSON.stringify(info, null, 2)} as const;\n`,
);

// admin-version.json reaches backend/public/admin/ only via the dist deploy
// (scripts/build-all.sh), so the manifest can never be newer than the bundle
// it describes — which is what would cause an endless "Update" banner.

console.log(`Admin build: v${info.version} · ${info.build}`);
