// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const ADMIN_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-09-24-130241-db7780d",
  "commit": "db7780d",
  "built_at": "2026-09-24T13:02:41.379Z"
} as const;
