// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const ADMIN_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-09-19-201319-e817d57",
  "commit": "e817d57",
  "built_at": "2026-09-19T20:13:19.397Z"
} as const;
