// Auto-generated by scripts/generate-version.mjs — do not edit manually.
export const ADMIN_BUILD_INFO = {
  "version": "1.0.0",
  "build": "2026-10-07-100016-34e043f",
  "commit": "34e043f",
  "built_at": "2026-10-07T10:00:16.373Z"
} as const;
