#!/usr/bin/env python3
"""The flame alone, for places where the whole logo is too loud.

Owner, 2026-10-07: dishes without a photo showed the full logo, and a
category of them read as a wall of identical logos. The menu now shows a
quiet cream circle with this flame, faded; the banner of a category without
a photo carries the same flame as a faint repeating pattern.

Reads the traced flame shapes from the order app's animatedLogoShapes.ts
(generated by brand-animated-logo.py from brand/logo-light.png), keeps the
flames and drops the ribbons under them, and writes:

  backend/public/brand/flame-mark.svg     one rust flame, transparent ground
  backend/public/brand/flame-pattern.svg  a tile of small cream flames for a
                                          dark banner, meant to repeat
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHAPES = os.path.join(ROOT, 'apps/online-order-web/src/components/animatedLogoShapes.ts')
RUST = '#B74B0C'

src = open(SHAPES).read()
paths = []
for key in ('flame_outer_left', 'flame_outer_right', 'flame_main', 'flame_inner'):
    d = re.search(key + r": '([^']+)'", src).group(1)
    # Each shape's first sub-path is the flame; any after it are the ribbons
    # that sit under the lettering.
    paths.append(d.split('zM')[0].rstrip('z') + 'z')

# The flames sit inside x 250..910, y 80..700 of the 1080 logo square.
VIEW = '240 70 680 640'
flame = ''.join(f'<path d="{d}"/>' for d in paths)

mark = (
    f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{VIEW}" role="img" aria-label="Bake &amp; Grill">'
    f'<g fill="{RUST}" fill-rule="evenodd">{flame}</g></svg>\n'
)
open(os.path.join(ROOT, 'backend/public/brand/flame-mark.svg'), 'w').write(mark)

# A 120 x 120 tile with two small flames, offset, so the repeat reads as a
# scatter rather than a grid. Cream on a dark banner; the page sets opacity.
tile = (
    '<svg xmlns="http://www.w3.org/2000/svg" width="120" height="120" viewBox="0 0 120 120">'
    f'<g fill="#F5EBC7">'
    f'<svg x="10" y="12" width="34" height="32" viewBox="{VIEW}">{flame}</svg>'
    f'<svg x="70" y="70" width="26" height="25" viewBox="{VIEW}">{flame}</svg>'
    '</g></svg>\n'
)
open(os.path.join(ROOT, 'backend/public/brand/flame-pattern.svg'), 'w').write(tile)
print('wrote flame-mark.svg and flame-pattern.svg')
