/**
 * Shared authentication helpers for all Playwright specs.
 *
 * Consolidates the injectAdminToken / injectCustomerAuth helpers that were
 * previously copy-pasted across admin-auth, checkout, and apps-smoke specs.
 */
import { type Page, expect } from '@playwright/test';

export const ADMIN_PIN     = process.env.ADMIN_PIN     ?? '1121';
export const TEST_PHONE    = process.env.TEST_PHONE    ?? '7972434';
export const TEST_PASSWORD = process.env.TEST_PASSWORD ?? 'Test@1234';

const ADMIN_API_URL   = process.env.ADMIN_API_URL   ?? 'http://localhost:8000';
const CUSTOMER_API_URL = ADMIN_API_URL;

// ── Admin auth ─────────────────────────────────────────────────────────────

/**
 * Obtain a staff Sanctum token via the PIN login endpoint and store it in
 * the page's localStorage so subsequent navigations are authenticated.
 */
export async function injectAdminToken(page: Page, pin?: string): Promise<string> {
  const usedPin = pin ?? ADMIN_PIN;

  // Get token from API
  const response = await page.request.post('/api/auth/staff/pin-login', {
    data: { pin: usedPin },
  });
  const data = await response.json().catch(() => ({}));
  const token: string = data.token ?? '';

  if (!token) {
    throw new Error(`injectAdminToken: PIN login failed — ${JSON.stringify(data)}`);
  }

  // Inject into localStorage
  await page.goto('/admin/');
  await page.waitForLoadState('networkidle');
  await page.evaluate((t: string) => {
    localStorage.setItem('admin_token', t);
  }, token);
  await page.goto('/admin/dashboard');
  await page.waitForLoadState('networkidle');

  return token;
}

/**
 * Perform a full UI PIN login on the admin numpad.
 * Slower than injectAdminToken but tests the actual UI flow.
 */
export async function adminLoginViaUI(page: Page, pin?: string): Promise<void> {
  const usedPin = pin ?? ADMIN_PIN;
  await page.goto('/admin/');
  await page.waitForSelector('button', { timeout: 15_000 });

  for (const digit of usedPin.split('')) {
    await page
      .locator('button')
      .filter({ hasText: new RegExp(`^\\s*${digit}\\s*$`) })
      .first()
      .click();
  }

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 });
}

// ── Customer auth ──────────────────────────────────────────────────────────

/**
 * Obtain a customer Sanctum token via the password login endpoint and inject
 * it into the page's localStorage under the `online_token` key.
 */
export async function injectCustomerToken(
  page: Page,
  phone?: string,
  password?: string,
): Promise<string> {
  const usedPhone    = phone    ?? `+960${TEST_PHONE}`;
  const usedPassword = password ?? TEST_PASSWORD;

  const response = await page.request.post('/api/auth/customer/login', {
    data: { phone: usedPhone, password: usedPassword },
  });
  const data = await response.json().catch(() => ({}));
  const token: string = data.token ?? '';

  if (!token) {
    return ''; // Caller may choose to skip instead of throw
  }

  await page.goto('/order/');
  await page.waitForLoadState('networkidle');
  await page.evaluate(
    ({ t, ph }: { t: string; ph: string }) => {
      localStorage.setItem('online_token', t);
      localStorage.setItem('online_customer_name', ph);
      window.dispatchEvent(new Event('auth_change'));
    },
    { t: token, ph: usedPhone },
  );
  await page.reload();
  await page.waitForLoadState('networkidle');

  return token;
}

/**
 * Load pre-saved customer storageState from disk (generated by customer-auth.spec.ts).
 * Prefer injectCustomerToken when a token is sufficient.
 */
export { STORAGE_STATE_PATH } from '../fixtures/auth';
