/**
 * Shared authentication helpers for all Playwright specs.
 *
 * Consolidates the injectAdminToken / injectCustomerAuth helpers that were
 * previously copy-pasted across admin-auth, checkout, and apps-smoke specs.
 */
import { type Page, expect } from '@playwright/test';

import { ADMIN_PIN, staffPinLoginBody, TEST_PHONE, TEST_PASSWORD } from '../fixtures/auth';
import { waitForCustomerSession } from './wait';

export { ADMIN_PIN, TEST_PHONE, TEST_PASSWORD };

const ADMIN_API_URL   = process.env.ADMIN_API_URL   ?? 'http://localhost:8000';
const CUSTOMER_API_URL = ADMIN_API_URL;

// ── Admin auth ─────────────────────────────────────────────────────────────

/**
 * Obtain a staff Sanctum token via the PIN login endpoint and store it in
 * the page's localStorage so subsequent navigations are authenticated.
 */
async function waitForAdminAuth(page: Page): Promise<boolean> {
  const resp = await page
    .waitForResponse(
      (r) => r.url().includes('/api/auth/me') && r.status() === 200,
      { timeout: 20_000 },
    )
    .catch(() => null);
  return resp !== null;
}

export async function gotoAdminWithToken(page: Page, token: string, path = '/admin/dashboard'): Promise<void> {
  await page.addInitScript((t: string) => {
    localStorage.setItem('admin_token', t);
  }, token);
  await page.goto(path, { waitUntil: 'domcontentloaded', timeout: 60_000 });

  let authed = await waitForAdminAuth(page);
  if (!authed) {
    await page.evaluate((t: string) => {
      localStorage.setItem('admin_token', t);
    }, token);
    await page.reload({ waitUntil: 'domcontentloaded' });
    authed = await waitForAdminAuth(page);
  }

  const body = (await page.textContent('body')) ?? '';
  if (/admin sign in|sign in →/i.test(body)) {
    await page.evaluate((t: string) => {
      localStorage.setItem('admin_token', t);
    }, token);
    await page.goto(path, { waitUntil: 'domcontentloaded', timeout: 60_000 });
    await waitForAdminAuth(page);
  }
}

/**
 * Obtain a staff Sanctum token via the PIN login endpoint and store it in
 * the page's localStorage so subsequent navigations are authenticated.
 */
export async function injectAdminToken(page: Page, pin?: string): Promise<string> {
  const usedPin = pin ?? ADMIN_PIN;

  const response = await page.request.post('/api/auth/staff/pin-login', {
    data: staffPinLoginBody(usedPin),
  });
  const data = await response.json().catch(() => ({}));
  const token: string = data.token ?? '';

  if (!token) {
    throw new Error(`injectAdminToken: PIN login failed — ${JSON.stringify(data)}`);
  }

  await gotoAdminWithToken(page, token, '/admin/dashboard');
  return token;
}

/**
 * Slower than injectAdminToken but tests the actual UI flow.
 */
export async function adminLoginViaUI(page: Page, pin?: string): Promise<void> {
  const usedPin = pin ?? ADMIN_PIN;
  await page.goto('/admin/');
  await page.waitForSelector('button', { timeout: 15_000 });

  for (const digit of usedPin.split('')) {
    await page
      .locator('button')
      .filter({ hasText: new RegExp(`^\\s*${digit}\\s*$`) })
      .first()
      .click();
  }

  await expect(page).toHaveURL(/\/dashboard/, { timeout: 15_000 });
}

// ── Customer auth ──────────────────────────────────────────────────────────

/**
 * Obtain a customer Sanctum token via the password login endpoint and inject
 * it into the page's localStorage under the `online_token` key.
 */
export async function injectCustomerToken(
  page: Page,
  phone?: string,
  password?: string,
): Promise<string> {
  const usedPhone    = phone    ?? `+960${TEST_PHONE}`;
  const usedPassword = password ?? TEST_PASSWORD;

  const response = await page.request.post('/api/auth/customer/login', {
    data: { phone: usedPhone, password: usedPassword },
  });
  const data = await response.json().catch(() => ({}));
  const token: string = data.token ?? '';

  if (!token) {
    return ''; // Caller may choose to skip instead of throw
  }

  await page.goto('/order/', { waitUntil: 'domcontentloaded' });
  await page.evaluate(
    ({ t, ph }: { t: string; ph: string }) => {
      localStorage.setItem('online_token', t);
      localStorage.setItem('online_customer_name', ph);
      window.dispatchEvent(new Event('auth_change'));
    },
    { t: token, ph: usedPhone.replace(/^\+960/, '') },
  );
  await page.reload({ waitUntil: 'domcontentloaded' });
  await waitForCustomerSession(page, usedPhone.replace(/^\+960/, ''));

  return token;
}

/**
 * Load pre-saved customer storageState from disk (generated by customer-auth.spec.ts).
 * Prefer injectCustomerToken when a token is sufficient.
 */
export { STORAGE_STATE_PATH } from '../fixtures/auth';
