#!/usr/bin/env node
/**
 * Reads e2e/report/results.json (Playwright JSON reporter output) and
 * produces e2e/report/QA-REPORT.md.
 *
 * Run: node -r dotenv/config e2e/helpers/qa-report.ts
 * Or:  npx ts-node e2e/helpers/qa-report.ts
 */
import fs from 'fs';
import path from 'path';

const RESULTS_FILE = path.resolve(__dirname, '../report/results.json');
const REPORT_FILE  = path.resolve(__dirname, '../report/QA-REPORT.md');

interface TestResult {
  title: string;
  status: 'passed' | 'failed' | 'skipped' | 'timedOut';
  duration: number;
  errors?: { message: string }[];
  attachments?: { name: string; path?: string; contentType: string }[];
}

interface Suite {
  title: string;
  file: string;
  specs: { title: string; tests: TestResult[] }[];
  suites?: Suite[];
}

interface PlaywrightReport {
  stats: {
    startTime: string;
    duration: number;
    expected: number;
    passed: number;
    failed: number;
    skipped: number;
  };
  suites: Suite[];
}

function collectTests(suite: Suite, file = suite.file): TestResult[] {
  const results: TestResult[] = [];
  for (const spec of suite.specs ?? []) {
    for (const test of spec.tests ?? []) {
      results.push({ ...test, title: `${suite.title} › ${spec.title}` });
    }
  }
  for (const sub of suite.suites ?? []) {
    results.push(...collectTests(sub, file));
  }
  return results;
}

function formatDuration(ms: number): string {
  if (ms < 1000) return `${ms}ms`;
  return `${(ms / 1000).toFixed(1)}s`;
}

function icon(status: string): string {
  return { passed: '✅', failed: '❌', skipped: '⏭️', timedOut: '⏱️' }[status] ?? '❓';
}

if (!fs.existsSync(RESULTS_FILE)) {
  console.error(`Results file not found: ${RESULTS_FILE}`);
  console.error('Run the test suite first: npx playwright test');
  process.exit(1);
}

const raw = fs.readFileSync(RESULTS_FILE, 'utf8');
const report: PlaywrightReport = JSON.parse(raw);

const allTests: TestResult[] = [];
for (const suite of report.suites) {
  allTests.push(...collectTests(suite));
}

const passed  = allTests.filter((t) => t.status === 'passed');
const failed  = allTests.filter((t) => t.status === 'failed' || t.status === 'timedOut');
const skipped = allTests.filter((t) => t.status === 'skipped');

const totalDuration = formatDuration(report.stats?.duration ?? 0);
const runDate = report.stats?.startTime
  ? new Date(report.stats.startTime).toLocaleString('en-MV', { timeZone: 'Indian/Maldives' })
  : new Date().toLocaleString();

let md = `# QA Report — test.bakeandgrill.mv

**Run date:** ${runDate}
**Total duration:** ${totalDuration}

## Summary

| Status  | Count |
|---------|-------|
| ✅ Passed  | ${passed.length} |
| ❌ Failed  | ${failed.length} |
| ⏭️ Skipped | ${skipped.length} |
| **Total**  | **${allTests.length}** |

---

## All Tests

| Test | Status | Duration |
|------|--------|----------|
`;

for (const t of allTests) {
  md += `| ${t.title} | ${icon(t.status)} ${t.status} | ${formatDuration(t.duration)} |\n`;
}

if (failed.length > 0) {
  md += `\n---\n\n## Failed Tests\n\n`;
  for (const t of failed) {
    md += `### ❌ ${t.title}\n\n`;
    if (t.errors?.length) {
      for (const err of t.errors) {
        const clean = err.message.replace(/\x1b\[[0-9;]*m/g, '').slice(0, 800);
        md += `\`\`\`\n${clean}\n\`\`\`\n\n`;
      }
    }
    const screenshots = t.attachments?.filter((a) => a.contentType.startsWith('image/'));
    if (screenshots?.length) {
      for (const s of screenshots) {
        md += `**Screenshot:** \`${s.path ?? s.name}\`\n\n`;
      }
    }
  }
}

md += `\n---\n\n## Recommended Fixes\n\n`;

if (failed.length === 0) {
  md += '_All tests passed — no fixes required._\n';
} else {
  md += `The following ${failed.length} test(s) need attention:\n\n`;
  for (const t of failed) {
    md += `- **${t.title}**: Check the screenshot and error above. Possible causes: selector mismatch, network timeout, or a real bug.\n`;
  }
  md += `\n> Re-run failed tests only: \`npx playwright test --grep "<test name>"\`\n`;
}

md += `\n---\n\n_Generated by \`e2e/helpers/qa-report.ts\`_\n`;

fs.mkdirSync(path.dirname(REPORT_FILE), { recursive: true });
fs.writeFileSync(REPORT_FILE, md, 'utf8');
console.log(`\n✅ QA report written to: ${REPORT_FILE}`);
console.log(`   Passed:  ${passed.length}`);
console.log(`   Failed:  ${failed.length}`);
console.log(`   Skipped: ${skipped.length}`);
