<?php

declare(strict_types=1);

namespace Tests\Contract;

use App\Models\Customer;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Hash;

/**
 * Contract/snapshot tests for the authentication API.
 *
 * Verifies response shapes for:
 *  - POST /api/auth/staff/pin-login (success)
 *  - POST /api/auth/customer/check-phone (new phone — no account)
 *  - POST /api/auth/customer/check-phone (existing phone with password)
 *  - GET  /api/auth/me (staff)
 */
class AuthContractTest extends ContractTestCase
{
    use RefreshDatabase;

    private string $ownerEmail = 'contract-owner@test.com';
    private string $ownerPin = '9988';

    /**
     * These fields contain values that vary between test runs and must be
     * normalised before comparison against the stored snapshot.
     */
    protected array $snapshotVolatileKeys = [
        'id', 'token', 'created_at', 'updated_at', 'permissions',
        'name', // generated by Faker
    ];

    protected function setUp(): void
    {
        parent::setUp();

        $this->makeOwner([
            'name' => 'Contract Owner',
            'email' => $this->ownerEmail,
            'pin_hash' => Hash::make($this->ownerPin),
        ]);
    }

    // ── POST /api/auth/staff/pin-login ────────────────────────────────────────

    public function test_staff_pin_login_response_shape(): void
    {
        $response = $this->postJson('/api/auth/staff/pin-login', [
            'username' => $this->ownerEmail,
            'pin' => $this->ownerPin,
        ])->assertStatus(200);

        $this->assertMatchesApiSnapshot($response, 'auth.staff.pin-login');
    }

    public function test_staff_pin_login_with_wrong_pin_returns_422(): void
    {
        $this->postJson('/api/auth/staff/pin-login', [
            'username' => $this->ownerEmail,
            'pin' => '0000',
        ])->assertStatus(422)
            ->assertJsonValidationErrors(['pin']);
    }

    public function test_staff_pin_login_without_username_returns_422(): void
    {
        $this->postJson('/api/auth/staff/pin-login', [
            'pin' => $this->ownerPin,
        ])->assertStatus(422);
    }

    // ── POST /api/auth/customer/check-phone ───────────────────────────────────

    public function test_check_phone_unknown_number_response_shape(): void
    {
        $response = $this->postJson('/api/auth/customer/check-phone', [
            'phone' => '+9607991234',
        ])->assertStatus(200);

        $this->assertMatchesApiSnapshot($response, 'auth.customer.check-phone.new');
    }

    public function test_check_phone_existing_customer_with_password_shape(): void
    {
        $customer = Customer::factory()->withPassword()->create([
            'phone' => '+9607991235',
        ]);

        $response = $this->postJson('/api/auth/customer/check-phone', [
            'phone' => '+9607991235',
        ])->assertStatus(200);

        $this->assertMatchesApiSnapshot($response, 'auth.customer.check-phone.existing');
    }

    public function test_check_phone_existing_customer_without_password_shape(): void
    {
        Customer::factory()->create([
            'phone' => '+9607991236',
            'password' => null,
        ]);

        $response = $this->postJson('/api/auth/customer/check-phone', [
            'phone' => '+9607991236',
        ])->assertStatus(200);

        $data = $response->json();
        $this->assertTrue($data['exists']);
        $this->assertFalse($data['has_password']);
    }

    // ── GET /api/auth/me ──────────────────────────────────────────────────────

    public function test_auth_me_response_shape(): void
    {
        $owner = $this->makeOwner(['name' => 'Me Test Owner', 'email' => 'me-test@owner.com']);
        $token = $this->staffHeaders($owner);

        $response = $this->getJson('/api/auth/me', $token)
            ->assertStatus(200);

        $this->assertMatchesApiSnapshot($response, 'auth.staff.me');
    }

    public function test_auth_me_requires_staff_token(): void
    {
        $customer = $this->makeCustomer();
        $token = $this->customerHeaders($customer);

        $this->getJson('/api/auth/me', $token)->assertStatus(403);
    }

    public function test_auth_me_requires_auth(): void
    {
        $this->getJson('/api/auth/me')->assertStatus(401);
    }
}
